const GeoLayout area_1_geo_140002D0[] = {
    GEO_NODE_SCREEN_AREA(0, 160, 120, 160, 120),
    GEO_OPEN_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_NODE_ORTHO(100),
            GEO_OPEN_NODE(),
                GEO_BACKGROUND_COLOR(0x0001),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_ZBUFFER(1),
        GEO_OPEN_NODE(),
            GEO_CAMERA_FRUSTUM(45, 128, 16384),
            GEO_OPEN_NODE(),
                GEO_CAMERA(0, 0, 0, 3200, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ASM(0, NULL),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_ASM(0, NULL),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_140001D0[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00080000),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, dl_07003330),
            GEO_DISPLAY_LIST(1, dl_070033D0),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_14000290[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00080000),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, dl_070061C8),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_140002B8[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00080000),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, dl_070061F8),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_140002E0[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00080000),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, dl_07006228),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_14000308[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00080000),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, dl_07006258),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_14000200[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00080000),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, dl_07003330),
            GEO_DISPLAY_LIST(1, dl_07003400),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_14000230[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00080000),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, dl_07003380),
            GEO_DISPLAY_LIST(1, dl_070033D0),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_14000260[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00080000),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, dl_07003380),
            GEO_DISPLAY_LIST(1, dl_07003400),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_14000330[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00080000),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, dl_07006288),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_14000358[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00080000),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, dl_070062B8),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout area_1_geo_14000380[] = {
    GEO_NODE_SCREEN_AREA(10, 160, 120, 160, 120),
    GEO_OPEN_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_NODE_ORTHO(100),
            GEO_OPEN_NODE(),
                GEO_BACKGROUND_COLOR(0x0001),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_ZBUFFER(1),
        GEO_OPEN_NODE(),
            GEO_CAMERA_FRUSTUM(45, 100, 25000),
            GEO_OPEN_NODE(),
                GEO_CAMERA(0, 0, 0, 1000, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_RENDER_OBJ(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_ASM(0, NULL),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_170002E0[] = {
    GEO_ASM(0, geo_mario_head_rotation),
    GEO_ROTATION_NODE(0, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
        GEO_OPEN_NODE(),
            GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(8, dl_040119A0),
                GEO_DISPLAY_LIST(8, dl_04011A90),
                GEO_DISPLAY_LIST(8, dl_04011B80),
                GEO_DISPLAY_LIST(8, dl_04011C70),
                GEO_DISPLAY_LIST(8, dl_04011D60),
                GEO_DISPLAY_LIST(8, dl_04011E50),
                GEO_DISPLAY_LIST(8, dl_04011F40),
                GEO_DISPLAY_LIST(8, dl_04012030),
                GEO_CLOSE_NODE(),
            GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(8, dl_040139E8),
                GEO_DISPLAY_LIST(8, dl_04013AB8),
                GEO_DISPLAY_LIST(8, dl_04013B88),
                GEO_DISPLAY_LIST(8, dl_04013C58),
                GEO_DISPLAY_LIST(8, dl_04013D28),
                GEO_DISPLAY_LIST(8, dl_04013DF8),
                GEO_DISPLAY_LIST(8, dl_04013EC8),
                GEO_DISPLAY_LIST(8, dl_04013F98),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, 65485, 65410, 22, 65496, 65401),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(4, dl_0401CA00),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, 65485, 126, 65514, 40, 65401),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(4, dl_0401CA00),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_1700041C[] = {
    GEO_SWITCH_CASE(1, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_hand_foot_scaler),
            GEO_SCALE(0, 0x00010000),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(8, dl_0400D8F0),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_04019CA0),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0400D8F0),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0400D8F0),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0400D8F0),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17000494[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_hand_foot_scaler),
            GEO_SCALE(0, 0x00010000),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(8, dl_0400E458),
                GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0, 0, 0, -32729, geo_switch_mario_hand_grab_pos),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0401A428),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0, 0, 0, -32729, geo_switch_mario_hand_grab_pos),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0401BF30),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0401B158),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0401B158),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(4, dl_0401B1D8),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_1700053C[] = {
    GEO_ANIMATED_PART(8, 0, 0, 0, NULL),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(8, 0, 0, 0, dl_0400CC98),
        GEO_OPEN_NODE(),
            GEO_ASM(0, NULL),
            GEO_ASM(0, geo_mario_tilt_torso),
            GEO_ROTATION_NODE(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(8, 68, 0, 0, dl_04010370),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(8, 87, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, geo_170002E0),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(8, 67, 65526, 79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(8, 0, 0, 0, dl_0400D1D8),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(8, 65, 0, 0, dl_0400D2F8),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, geo_1700041C),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(8, 68, 65526, 65457, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(8, 0, 0, 0, dl_0400DDE8),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(8, 65, 0, 0, dl_0400DF08),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, geo_17000494),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(8, 13, 65528, 42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(8, 0, 0, 0, dl_0400E7B0),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(8, 89, 0, 0, dl_0400E918),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(8, 67, 0, 0, dl_0400ECA0),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(8, 13, 65528, 65494, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(8, 0, 0, 0, dl_0400EFB8),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(8, 89, 0, 0, dl_0400F1D8),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(8, 67, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, geo_mario_hand_foot_scaler),
                            GEO_SCALE(0, 0x00010000),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(8, dl_0400F4E8),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17000DEC[] = {
    GEO_ASM(0, geo_mario_head_rotation),
    GEO_ROTATION_NODE(0, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
        GEO_OPEN_NODE(),
            GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(5, dl_040119A0),
                GEO_DISPLAY_LIST(5, dl_04011A90),
                GEO_DISPLAY_LIST(5, dl_04011B80),
                GEO_DISPLAY_LIST(5, dl_04011C70),
                GEO_DISPLAY_LIST(5, dl_04011D60),
                GEO_DISPLAY_LIST(5, dl_04011E50),
                GEO_DISPLAY_LIST(5, dl_04011F40),
                GEO_DISPLAY_LIST(5, dl_04012030),
                GEO_CLOSE_NODE(),
            GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(5, dl_040139E8),
                GEO_DISPLAY_LIST(5, dl_04013AB8),
                GEO_DISPLAY_LIST(5, dl_04013B88),
                GEO_DISPLAY_LIST(5, dl_04013C58),
                GEO_DISPLAY_LIST(5, dl_04013D28),
                GEO_DISPLAY_LIST(5, dl_04013DF8),
                GEO_DISPLAY_LIST(5, dl_04013EC8),
                GEO_DISPLAY_LIST(5, dl_04013F98),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, 65485, 65410, 22, 65496, 65401),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(5, dl_0401CAB8),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, 65485, 126, 65514, 40, 65401),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(5, dl_0401CAB8),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17000F28[] = {
    GEO_SWITCH_CASE(1, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_hand_foot_scaler),
            GEO_SCALE(0, 0x00010000),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(5, dl_0400D8F0),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_04019CA0),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0400D8F0),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0400D8F0),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0400D8F0),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17000FA0[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_hand_foot_scaler),
            GEO_SCALE(0, 0x00010000),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(5, dl_0400E458),
                GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0, 0, 0, -32729, geo_switch_mario_hand_grab_pos),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0401A428),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0, 0, 0, -32729, geo_switch_mario_hand_grab_pos),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0401BF30),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0401B158),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0401B158),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(4, dl_0401B1D8),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17001048[] = {
    GEO_ANIMATED_PART(5, 0, 0, 0, NULL),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(5, 0, 0, 0, dl_0400CC98),
        GEO_OPEN_NODE(),
            GEO_ASM(0, NULL),
            GEO_ASM(0, geo_mario_tilt_torso),
            GEO_ROTATION_NODE(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(5, 68, 0, 0, dl_04010370),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(5, 87, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, geo_17000DEC),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(5, 67, 65526, 79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 0, 0, 0, dl_0400D1D8),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(5, 65, 0, 0, dl_0400D2F8),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, geo_17000F28),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(5, 68, 65526, 65457, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 0, 0, 0, dl_0400DDE8),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(5, 65, 0, 0, dl_0400DF08),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, geo_17000FA0),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(5, 13, 65528, 42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(5, 0, 0, 0, dl_0400E7B0),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(5, 89, 0, 0, dl_0400E918),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 67, 0, 0, dl_0400ECA0),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(5, 13, 65528, 65494, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(5, 0, 0, 0, dl_0400EFB8),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(5, 89, 0, 0, dl_0400F1D8),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 67, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, geo_mario_hand_foot_scaler),
                            GEO_SCALE(0, 0x00010000),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(5, dl_0400F4E8),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_170018F8[] = {
    GEO_ASM(0, geo_mario_head_rotation),
    GEO_ROTATION_NODE(0, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(8, dl_04012120),
            GEO_DISPLAY_LIST(8, dl_04014068),
            GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, 65485, 65410, 22, 65496, 65401),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(4, dl_0401CB70),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, 65485, 126, 65514, 40, 65401),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(4, dl_0401CB70),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_170019A4[] = {
    GEO_SWITCH_CASE(1, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_hand_foot_scaler),
            GEO_SCALE(0, 0x00010000),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(8, dl_0400D758),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_04019A68),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0400D758),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0400D758),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0400D758),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17001A1C[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_hand_foot_scaler),
            GEO_SCALE(0, 0x00010000),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(8, dl_0400E478),
                GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0, 0, 0, -32729, geo_switch_mario_hand_grab_pos),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0401A448),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0, 0, 0, -32729, geo_switch_mario_hand_grab_pos),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0401BC80),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0401B230),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0401B230),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(4, dl_0401B278),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17001AC4[] = {
    GEO_ANIMATED_PART(8, 0, 0, 0, NULL),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(8, 0, 0, 0, dl_0400CCC8),
        GEO_OPEN_NODE(),
            GEO_ASM(0, NULL),
            GEO_ASM(0, geo_mario_tilt_torso),
            GEO_ROTATION_NODE(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(8, 68, 0, 0, dl_040103F0),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(8, 87, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, geo_170018F8),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(8, 67, 65526, 79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(8, 0, 0, 0, dl_0400D090),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(8, 65, 0, 0, dl_0400D2F8),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, geo_170019A4),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(8, 68, 65526, 65457, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(8, 0, 0, 0, dl_0400DCA0),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(8, 65, 0, 0, dl_0400DF08),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, geo_17001A1C),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(8, 13, 65528, 42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(8, 0, 0, 0, dl_0400E7E0),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(8, 89, 0, 0, dl_0400E918),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(8, 67, 0, 0, dl_0400EBB8),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(8, 13, 65528, 65494, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(8, 0, 0, 0, dl_0400EEB0),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(8, 89, 0, 0, dl_0400F1D8),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(8, 67, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, geo_mario_hand_foot_scaler),
                            GEO_SCALE(0, 0x00010000),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(8, dl_0400F528),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_170022E4[] = {
    GEO_ASM(0, geo_mario_head_rotation),
    GEO_ROTATION_NODE(0, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(5, dl_04012120),
            GEO_DISPLAY_LIST(5, dl_04014068),
            GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, 65485, 65410, 22, 65496, 65401),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(5, dl_0401CC28),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, 65485, 126, 65514, 40, 65401),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(5, dl_0401CC28),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17002390[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_hand_foot_scaler),
            GEO_SCALE(0, 0x00010000),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(5, dl_0400D758),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_04019A68),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0400D758),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0400D758),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0400D758),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17002408[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_hand_foot_scaler),
            GEO_SCALE(0, 0x00010000),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(5, dl_0400E478),
                GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0, 0, 0, -32729, geo_switch_mario_hand_grab_pos),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0401A448),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0, 0, 0, -32729, geo_switch_mario_hand_grab_pos),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0401BC80),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0401B230),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0401B230),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(4, dl_0401B278),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_170024B0[] = {
    GEO_ANIMATED_PART(5, 0, 0, 0, NULL),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(5, 0, 0, 0, dl_0400CCC8),
        GEO_OPEN_NODE(),
            GEO_ASM(0, NULL),
            GEO_ASM(0, geo_mario_tilt_torso),
            GEO_ROTATION_NODE(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(5, 68, 0, 0, dl_040103F0),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(5, 87, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, geo_170022E4),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(5, 67, 65526, 79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 0, 0, 0, dl_0400D090),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(5, 65, 0, 0, dl_0400D2F8),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, geo_17002390),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(5, 68, 65526, 65457, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 0, 0, 0, dl_0400DCA0),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(5, 65, 0, 0, dl_0400DF08),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, geo_17002408),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(5, 13, 65528, 42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(5, 0, 0, 0, dl_0400E7E0),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(5, 89, 0, 0, dl_0400E918),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 67, 0, 0, dl_0400EBB8),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(5, 13, 65528, 65494, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(5, 0, 0, 0, dl_0400EEB0),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(5, 89, 0, 0, dl_0400F1D8),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 67, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, geo_mario_hand_foot_scaler),
                            GEO_SCALE(0, 0x00010000),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(5, dl_0400F528),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17002CE0[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
    GEO_OPEN_NODE(),
        GEO_BRANCH(1, geo_1700053C),
        GEO_BRANCH(1, geo_17001048),
        GEO_BRANCH(1, geo_17001AC4),
        GEO_BRANCH(1, geo_170024B0),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_170006F8[] = {
    GEO_SWITCH_CASE(1, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_hand_foot_scaler),
            GEO_SCALE(0, 0x00010000),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(8, dl_04014DC0),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_04019CA0),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_04014DC0),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_04014DC0),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_04014DC0),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17000770[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_hand_foot_scaler),
            GEO_SCALE(0, 0x00010000),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(8, dl_040154E0),
                GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0, 0, 0, -32729, geo_switch_mario_hand_grab_pos),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0401A428),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0, 0, 0, -32729, geo_switch_mario_hand_grab_pos),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0401BF30),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0401B158),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0401B158),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(4, dl_0401B1D8),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17000818[] = {
    GEO_ANIMATED_PART(8, 0, 0, 0, NULL),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(8, 0, 0, 0, dl_04014638),
        GEO_OPEN_NODE(),
            GEO_ASM(0, NULL),
            GEO_ASM(0, geo_mario_tilt_torso),
            GEO_ROTATION_NODE(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(8, 68, 0, 0, dl_040168C8),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(8, 87, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, geo_170002E0),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(8, 67, 65526, 79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(8, 0, 0, 0, dl_04014840),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(8, 65, 0, 0, dl_04014950),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, geo_170006F8),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(8, 68, 65526, 65457, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(8, 0, 0, 0, dl_04014F40),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(8, 65, 0, 0, dl_04015050),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, geo_17000770),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(8, 13, 65528, 42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(8, 0, 0, 0, dl_040156B0),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(8, 89, 0, 0, dl_04015848),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(8, 67, 0, 0, dl_04015B60),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(8, 13, 65528, 65494, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(8, 0, 0, 0, dl_04015D00),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(8, 89, 0, 0, dl_04015E10),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(8, 67, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, geo_mario_hand_foot_scaler),
                            GEO_SCALE(0, 0x00010000),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(8, dl_040160C8),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17001204[] = {
    GEO_SWITCH_CASE(1, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_hand_foot_scaler),
            GEO_SCALE(0, 0x00010000),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(5, dl_04014DC0),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_04019CA0),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_04014DC0),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_04014DC0),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_04014DC0),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_1700127C[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_hand_foot_scaler),
            GEO_SCALE(0, 0x00010000),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(5, dl_040154E0),
                GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0, 0, 0, -32729, geo_switch_mario_hand_grab_pos),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0401A428),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0, 0, 0, -32729, geo_switch_mario_hand_grab_pos),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0401BF30),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0401B158),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0401B158),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(4, dl_0401B1D8),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17001324[] = {
    GEO_ANIMATED_PART(5, 0, 0, 0, NULL),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(5, 0, 0, 0, dl_04014638),
        GEO_OPEN_NODE(),
            GEO_ASM(0, NULL),
            GEO_ASM(0, geo_mario_tilt_torso),
            GEO_ROTATION_NODE(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(5, 68, 0, 0, dl_040168C8),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(5, 87, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, geo_17000DEC),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(5, 67, 65526, 79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 0, 0, 0, dl_04014840),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(5, 65, 0, 0, dl_04014950),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, geo_17001204),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(5, 68, 65526, 65457, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 0, 0, 0, dl_04014F40),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(5, 65, 0, 0, dl_04015050),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, geo_1700127C),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(5, 13, 65528, 42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(5, 0, 0, 0, dl_040156B0),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(5, 89, 0, 0, dl_04015848),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 67, 0, 0, dl_04015B60),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(5, 13, 65528, 65494, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(5, 0, 0, 0, dl_04015D00),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(5, 89, 0, 0, dl_04015E10),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 67, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, geo_mario_hand_foot_scaler),
                            GEO_SCALE(0, 0x00010000),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(5, dl_040160C8),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17001C80[] = {
    GEO_SWITCH_CASE(1, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_hand_foot_scaler),
            GEO_SCALE(0, 0x00010000),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(8, dl_04014C90),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_04019A68),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_04014C90),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_04014C90),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_04014C90),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17001CF8[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_hand_foot_scaler),
            GEO_SCALE(0, 0x00010000),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(8, dl_04015500),
                GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0, 0, 0, -32729, geo_switch_mario_hand_grab_pos),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0401A448),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0, 0, 0, -32729, geo_switch_mario_hand_grab_pos),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0401BC80),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0401B230),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0401B230),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(4, dl_0401B278),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17001DA0[] = {
    GEO_ANIMATED_PART(8, 0, 0, 0, NULL),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(8, 0, 0, 0, dl_04014668),
        GEO_OPEN_NODE(),
            GEO_ASM(0, NULL),
            GEO_ASM(0, geo_mario_tilt_torso),
            GEO_ROTATION_NODE(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(8, 68, 0, 0, dl_04016948),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(8, 87, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, geo_170018F8),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(8, 67, 65526, 79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(8, 0, 0, 0, dl_040147D0),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(8, 65, 0, 0, dl_04014950),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, geo_17001C80),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(8, 68, 65526, 65457, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(8, 0, 0, 0, dl_04014ED0),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(8, 65, 0, 0, dl_04015050),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, geo_17001CF8),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(8, 13, 65528, 42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(8, 0, 0, 0, dl_040156E0),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(8, 89, 0, 0, dl_04015848),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(8, 67, 0, 0, dl_04015A98),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(8, 13, 65528, 65494, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(8, 0, 0, 0, dl_04015C70),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(8, 89, 0, 0, dl_04015E10),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(8, 67, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, geo_mario_hand_foot_scaler),
                            GEO_SCALE(0, 0x00010000),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(8, dl_04016108),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_1700266C[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_hand_foot_scaler),
            GEO_SCALE(0, 0x00010000),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(5, dl_04014C90),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_04019A68),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_04014C90),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_04014C90),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_04014C90),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_170026E4[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_hand_foot_scaler),
            GEO_SCALE(0, 0x00010000),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(5, dl_04015500),
                GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0, 0, 0, -32729, geo_switch_mario_hand_grab_pos),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0401A448),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0, 0, 0, -32729, geo_switch_mario_hand_grab_pos),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0401BC80),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0401B230),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0401B230),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(4, dl_0401B278),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_1700278C[] = {
    GEO_ANIMATED_PART(5, 0, 0, 0, NULL),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(5, 0, 0, 0, dl_04014668),
        GEO_OPEN_NODE(),
            GEO_ASM(0, NULL),
            GEO_ASM(0, geo_mario_tilt_torso),
            GEO_ROTATION_NODE(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(5, 68, 0, 0, dl_04016948),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(5, 87, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, geo_170022E4),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(5, 67, 65526, 79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 0, 0, 0, dl_040147D0),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(5, 65, 0, 0, dl_04014950),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, geo_1700266C),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(5, 68, 65526, 65457, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 0, 0, 0, dl_04014ED0),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(5, 65, 0, 0, dl_04015050),
                            GEO_OPEN_NODE(),
                                GEO_SWITCH_CASE(0, geo_switch_mario_hand),
                                GEO_OPEN_NODE(),
                                    GEO_BRANCH(1, geo_170026E4),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(5, 13, 65528, 42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(5, 0, 0, 0, dl_040156E0),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(5, 89, 0, 0, dl_04015848),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 67, 0, 0, dl_04015A98),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(5, 13, 65528, 65494, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(5, 0, 0, 0, dl_04015C70),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(5, 89, 0, 0, dl_04015E10),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 67, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, geo_mario_hand_foot_scaler),
                            GEO_SCALE(0, 0x00010000),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(5, dl_04016108),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17002D14[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
    GEO_OPEN_NODE(),
        GEO_BRANCH(1, geo_17000818),
        GEO_BRANCH(1, geo_17001324),
        GEO_BRANCH(1, geo_17001DA0),
        GEO_BRANCH(1, geo_1700278C),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_170009D4[] = {
    GEO_ASM(0, geo_mario_head_rotation),
    GEO_ROTATION_NODE(0, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
        GEO_OPEN_NODE(),
            GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(8, dl_04018460),
                GEO_DISPLAY_LIST(8, dl_04018530),
                GEO_DISPLAY_LIST(8, dl_04018600),
                GEO_DISPLAY_LIST(8, dl_040186D0),
                GEO_DISPLAY_LIST(8, dl_040187A0),
                GEO_DISPLAY_LIST(8, dl_04018870),
                GEO_DISPLAY_LIST(8, dl_04018940),
                GEO_DISPLAY_LIST(8, dl_04018A10),
                GEO_CLOSE_NODE(),
            GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(8, dl_04018F90),
                GEO_DISPLAY_LIST(8, dl_04019040),
                GEO_DISPLAY_LIST(8, dl_040190F0),
                GEO_DISPLAY_LIST(8, dl_040191A0),
                GEO_DISPLAY_LIST(8, dl_04019250),
                GEO_DISPLAY_LIST(8, dl_04019300),
                GEO_DISPLAY_LIST(8, dl_040193B0),
                GEO_DISPLAY_LIST(8, dl_04019460),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, 65485, 65410, 22, 65496, 65401),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(4, dl_0401CA00),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, 65485, 126, 65514, 40, 65401),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(4, dl_0401CA00),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17000B10[] = {
    GEO_SWITCH_CASE(1, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_hand_foot_scaler),
            GEO_SCALE(0, 0x00010000),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(8, dl_04016E80),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_04019CA0),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_04016E80),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_04016E80),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_04016E80),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17000B88[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_hand_foot_scaler),
            GEO_SCALE(0, 0x00010000),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(8, dl_040171C0),
                GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0, 0, 0, -32729, geo_switch_mario_hand_grab_pos),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0401A428),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0, 0, 0, -32729, geo_switch_mario_hand_grab_pos),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0401BF30),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0401B158),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0401B158),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(4, dl_0401B1D8),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17000C30[] = {
    GEO_ANIMATED_PART(8, 0, 0, 0, NULL),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(8, 0, 0, 0, dl_04016AB8),
        GEO_OPEN_NODE(),
            GEO_ASM(0, NULL),
            GEO_ASM(0, geo_mario_tilt_torso),
            GEO_ROTATION_NODE(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(8, 68, 0, 0, dl_04017EA0),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(8, 87, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, geo_170009D4),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(8, 67, 65526, 79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(8, 0, 0, 0, dl_04016C70),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(8, 65, 0, 0, dl_04016D50),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, geo_17000B10),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(8, 68, 65526, 65457, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(8, 0, 0, 0, dl_04016FB0),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(8, 65, 0, 0, dl_04017090),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, geo_17000B88),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(8, 13, 65528, 42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(8, 0, 0, 0, dl_04017360),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(8, 89, 0, 0, dl_040174E8),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(8, 67, 0, 0, dl_040176A8),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(8, 13, 65528, 65494, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(8, 0, 0, 0, dl_04017818),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(8, 89, 0, 0, dl_04017918),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(8, 67, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, geo_mario_hand_foot_scaler),
                            GEO_SCALE(0, 0x00010000),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(8, dl_04017AD8),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_170014E0[] = {
    GEO_ASM(0, geo_mario_head_rotation),
    GEO_ROTATION_NODE(0, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
        GEO_OPEN_NODE(),
            GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(5, dl_04018460),
                GEO_DISPLAY_LIST(5, dl_04018530),
                GEO_DISPLAY_LIST(5, dl_04018600),
                GEO_DISPLAY_LIST(5, dl_040186D0),
                GEO_DISPLAY_LIST(5, dl_040187A0),
                GEO_DISPLAY_LIST(5, dl_04018870),
                GEO_DISPLAY_LIST(5, dl_04018940),
                GEO_DISPLAY_LIST(5, dl_04018A10),
                GEO_CLOSE_NODE(),
            GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(5, dl_04018F90),
                GEO_DISPLAY_LIST(5, dl_04019040),
                GEO_DISPLAY_LIST(5, dl_040190F0),
                GEO_DISPLAY_LIST(5, dl_040191A0),
                GEO_DISPLAY_LIST(5, dl_04019250),
                GEO_DISPLAY_LIST(5, dl_04019300),
                GEO_DISPLAY_LIST(5, dl_040193B0),
                GEO_DISPLAY_LIST(5, dl_04019460),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, 65485, 65410, 22, 65496, 65401),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(5, dl_0401CAB8),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, 65485, 126, 65514, 40, 65401),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(5, dl_0401CAB8),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_1700161C[] = {
    GEO_SWITCH_CASE(1, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_hand_foot_scaler),
            GEO_SCALE(0, 0x00010000),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(5, dl_04016E80),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_04019CA0),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_04016E80),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_04016E80),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_04016E80),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17001694[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_hand_foot_scaler),
            GEO_SCALE(0, 0x00010000),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(5, dl_040171C0),
                GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0, 0, 0, -32729, geo_switch_mario_hand_grab_pos),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0401A428),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0, 0, 0, -32729, geo_switch_mario_hand_grab_pos),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0401BF30),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0401B158),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0401B158),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(4, dl_0401B1D8),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_1700173C[] = {
    GEO_ANIMATED_PART(5, 0, 0, 0, NULL),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(5, 0, 0, 0, dl_04016AB8),
        GEO_OPEN_NODE(),
            GEO_ASM(0, NULL),
            GEO_ASM(0, geo_mario_tilt_torso),
            GEO_ROTATION_NODE(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(5, 68, 0, 0, dl_04017EA0),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(5, 87, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, geo_170014E0),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(5, 67, 65526, 79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 0, 0, 0, dl_04016C70),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(5, 65, 0, 0, dl_04016D50),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, geo_1700161C),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(5, 68, 65526, 65457, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 0, 0, 0, dl_04016FB0),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(5, 65, 0, 0, dl_04017090),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, geo_17001694),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(5, 13, 65528, 42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(5, 0, 0, 0, dl_04017360),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(5, 89, 0, 0, dl_040174E8),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 67, 0, 0, dl_040176A8),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(5, 13, 65528, 65494, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(5, 0, 0, 0, dl_04017818),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(5, 89, 0, 0, dl_04017918),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 67, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, geo_mario_hand_foot_scaler),
                            GEO_SCALE(0, 0x00010000),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(5, dl_04017AD8),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17001F5C[] = {
    GEO_ASM(0, geo_mario_head_rotation),
    GEO_ROTATION_NODE(0, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(8, dl_04018AE0),
            GEO_DISPLAY_LIST(8, dl_04019510),
            GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, 65485, 65410, 22, 65496, 65401),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(4, dl_0401CB70),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, 65485, 126, 65514, 40, 65401),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(4, dl_0401CB70),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17002008[] = {
    GEO_SWITCH_CASE(1, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_hand_foot_scaler),
            GEO_SCALE(0, 0x00010000),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(8, dl_04016E20),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_04019A68),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_04016E20),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_04016E20),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_04016E20),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17002080[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_hand_foot_scaler),
            GEO_SCALE(0, 0x00010000),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(8, dl_040171E0),
                GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0, 0, 0, -32729, geo_switch_mario_hand_grab_pos),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0401A448),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0, 0, 0, -32729, geo_switch_mario_hand_grab_pos),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0401BC80),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0401B230),
        GEO_ANIMATED_PART(8, 60, 0, 0, dl_0401B230),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(4, dl_0401B278),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17002128[] = {
    GEO_ANIMATED_PART(8, 0, 0, 0, NULL),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(8, 0, 0, 0, dl_04016AE8),
        GEO_OPEN_NODE(),
            GEO_ASM(0, NULL),
            GEO_ASM(0, geo_mario_tilt_torso),
            GEO_ROTATION_NODE(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(8, 68, 0, 0, dl_04017F20),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(8, 87, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, geo_17001F5C),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(8, 67, 65526, 79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(8, 0, 0, 0, dl_04016C20),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(8, 65, 0, 0, dl_04016D50),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, geo_17002008),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(8, 68, 65526, 65457, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(8, 0, 0, 0, dl_04016F60),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(8, 65, 0, 0, dl_04017090),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, geo_17002080),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(8, 13, 65528, 42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(8, 0, 0, 0, dl_04017390),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(8, 89, 0, 0, dl_040174E8),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(8, 67, 0, 0, dl_04017638),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(8, 13, 65528, 65494, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(8, 0, 0, 0, dl_040177A8),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(8, 89, 0, 0, dl_04017918),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(8, 67, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, geo_mario_hand_foot_scaler),
                            GEO_SCALE(0, 0x00010000),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(8, dl_04017B18),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17002958[] = {
    GEO_ASM(0, geo_mario_head_rotation),
    GEO_ROTATION_NODE(0, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(5, dl_04018AE0),
            GEO_DISPLAY_LIST(5, dl_04019510),
            GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, 65485, 65410, 22, 65496, 65401),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(5, dl_0401CC28),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_TRANSLATE_ROTATE(0, 142, 65485, 126, 65514, 40, 65401),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
            GEO_ROTATION_NODE(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(5, dl_0401CC28),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17002A04[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(1, geo_mario_hand_foot_scaler),
            GEO_SCALE(0, 0x00010000),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(5, dl_04016E20),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_04019A68),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_04016E20),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_04016E20),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_04016E20),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17002A7C[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_hand),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mario_hand_foot_scaler),
            GEO_SCALE(0, 0x00010000),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(5, dl_040171E0),
                GEO_CLOSE_NODE(),
            GEO_HELD_OBJECT(0, 0, 0, -32729, geo_switch_mario_hand_grab_pos),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0401A448),
        GEO_OPEN_NODE(),
            GEO_HELD_OBJECT(0, 0, 0, -32729, geo_switch_mario_hand_grab_pos),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0401BC80),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0401B230),
        GEO_ANIMATED_PART(5, 60, 0, 0, dl_0401B230),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(4, dl_0401B278),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17002B24[] = {
    GEO_ANIMATED_PART(5, 0, 0, 0, NULL),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(5, 0, 0, 0, dl_04016AE8),
        GEO_OPEN_NODE(),
            GEO_ASM(0, NULL),
            GEO_ASM(0, geo_mario_tilt_torso),
            GEO_ROTATION_NODE(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(5, 68, 0, 0, dl_04017F20),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(5, 87, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BRANCH(1, geo_17002958),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(5, 67, 65526, 79, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 0, 0, 0, dl_04016C20),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(5, 65, 0, 0, dl_04016D50),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, geo_17002A04),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(5, 68, 65526, 65457, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 0, 0, 0, dl_04016F60),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(5, 65, 0, 0, dl_04017090),
                            GEO_OPEN_NODE(),
                                GEO_BRANCH(1, geo_17002A7C),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(5, 13, 65528, 42, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(5, 0, 0, 0, dl_04017390),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(5, 89, 0, 0, dl_040174E8),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 67, 0, 0, dl_04017638),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(5, 13, 65528, 65494, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(5, 0, 0, 0, dl_040177A8),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(5, 89, 0, 0, dl_04017918),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 67, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ASM(2, geo_mario_hand_foot_scaler),
                            GEO_SCALE(0, 0x00010000),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(5, dl_04017B18),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17002D48[] = {
    GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
    GEO_OPEN_NODE(),
        GEO_BRANCH(1, geo_17000C30),
        GEO_BRANCH(1, geo_1700173C),
        GEO_BRANCH(1, geo_17002128),
        GEO_BRANCH(1, geo_17002B24),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17002D7C[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_RENDER_RANGE(-2048, 600),
        GEO_OPEN_NODE(),
            GEO_BRANCH(1, geo_17002CE0),
            GEO_CLOSE_NODE(),
        GEO_RENDER_RANGE(600, 1600),
        GEO_OPEN_NODE(),
            GEO_BRANCH(1, geo_17002D14),
            GEO_CLOSE_NODE(),
        GEO_RENDER_RANGE(1600, 32767),
        GEO_OPEN_NODE(),
            GEO_BRANCH(1, geo_17002D48),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout geo_17002DD4[] = {
    GEO_SHADOW(1, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_mirror_mario_backface_culling),
            GEO_ASM(0, geo_mirror_mario_set_alpha),
            GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
            GEO_OPEN_NODE(),
                GEO_BRANCH(1, geo_17002CE0),
                GEO_BRANCH(1, geo_17002D7C),
                GEO_CLOSE_NODE(),
            GEO_ASM(1, geo_mirror_mario_backface_culling),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_17000038[] = {
    GEO_SWITCH_CASE(7, geo_switch_anim_state),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(5, dl_04021718),
        GEO_DISPLAY_LIST(5, dl_04021730),
        GEO_DISPLAY_LIST(5, dl_04021748),
        GEO_DISPLAY_LIST(5, dl_04021760),
        GEO_DISPLAY_LIST(5, dl_04021778),
        GEO_DISPLAY_LIST(5, dl_04021790),
        GEO_DISPLAY_LIST(5, dl_040217A8),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_170001BC[] = {
    GEO_SWITCH_CASE(12, geo_switch_anim_state),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(4, dl_0402A570),
        GEO_DISPLAY_LIST(4, dl_0402A570),
        GEO_DISPLAY_LIST(4, dl_0402A558),
        GEO_DISPLAY_LIST(4, dl_0402A558),
        GEO_DISPLAY_LIST(4, dl_0402A540),
        GEO_DISPLAY_LIST(4, dl_0402A540),
        GEO_DISPLAY_LIST(4, dl_0402A528),
        GEO_DISPLAY_LIST(4, dl_0402A528),
        GEO_DISPLAY_LIST(4, dl_0402A510),
        GEO_DISPLAY_LIST(4, dl_0402A510),
        GEO_DISPLAY_LIST(4, dl_0402A4F8),
        GEO_DISPLAY_LIST(4, dl_0402A4F8),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_17000000[] = {
    GEO_SWITCH_CASE(1, geo_switch_anim_state),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(4, dl_0401DD60),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_1700009C[] = {
    GEO_SWITCH_CASE(6, geo_switch_anim_state),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(5, dl_040251F8),
        GEO_DISPLAY_LIST(5, dl_04025210),
        GEO_DISPLAY_LIST(5, dl_04025228),
        GEO_DISPLAY_LIST(5, dl_04025240),
        GEO_DISPLAY_LIST(5, dl_04025258),
        GEO_DISPLAY_LIST(5, dl_04025270),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_17000124[] = {
    GEO_SWITCH_CASE(6, geo_switch_anim_state),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(5, dl_040273F0),
        GEO_DISPLAY_LIST(5, dl_04027408),
        GEO_DISPLAY_LIST(5, dl_04027420),
        GEO_DISPLAY_LIST(5, dl_04027438),
        GEO_DISPLAY_LIST(5, dl_04027420),
        GEO_DISPLAY_LIST(5, dl_04027408),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_17000230[] = {
    GEO_SWITCH_CASE(8, geo_switch_anim_state),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(4, dl_04032640),
        GEO_DISPLAY_LIST(4, dl_04032658),
        GEO_DISPLAY_LIST(4, dl_04032670),
        GEO_DISPLAY_LIST(4, dl_04032688),
        GEO_DISPLAY_LIST(4, dl_040326A0),
        GEO_DISPLAY_LIST(4, dl_040326B8),
        GEO_DISPLAY_LIST(4, dl_040326D0),
        GEO_DISPLAY_LIST(4, dl_040326E8),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_17000168[] = {
    GEO_SWITCH_CASE(8, geo_switch_anim_state),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(5, dl_040273F0),
        GEO_DISPLAY_LIST(5, dl_04027408),
        GEO_DISPLAY_LIST(5, dl_04027420),
        GEO_DISPLAY_LIST(5, dl_04027438),
        GEO_DISPLAY_LIST(5, dl_04027438),
        GEO_DISPLAY_LIST(5, dl_04027438),
        GEO_DISPLAY_LIST(5, dl_04027438),
        GEO_DISPLAY_LIST(5, dl_04027438),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_1600013C[] = {
    GEO_SHADOW(1, 180, 50),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(8, geo_switch_anim_state),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(4, dl_03007800),
            GEO_DISPLAY_LIST(4, dl_03007800),
            GEO_DISPLAY_LIST(4, dl_03007828),
            GEO_DISPLAY_LIST(4, dl_03007828),
            GEO_DISPLAY_LIST(4, dl_03007850),
            GEO_DISPLAY_LIST(4, dl_03007850),
            GEO_DISPLAY_LIST(4, dl_03007878),
            GEO_DISPLAY_LIST(4, dl_03007878),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_16000EA0[] = {
    GEO_SHADOW(1, 155, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, dl_0302B870),
            GEO_DISPLAY_LIST(4, dl_0302BA18),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_16000F6C[] = {
    GEO_SHADOW(1, 155, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(5, dl_0302C620),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_16000FB4[] = {
    GEO_SHADOW(1, 200, 60),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, dl_0302DA48),
            GEO_DISPLAY_LIST(1, dl_0302DD08),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_16000B2C[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(8, geo_switch_anim_state),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(5, dl_0301B3B0),
            GEO_DISPLAY_LIST(5, dl_0301B3C8),
            GEO_DISPLAY_LIST(5, dl_0301B3E0),
            GEO_DISPLAY_LIST(5, dl_0301B3F8),
            GEO_DISPLAY_LIST(5, dl_0301B410),
            GEO_DISPLAY_LIST(5, dl_0301B428),
            GEO_DISPLAY_LIST(5, dl_0301B440),
            GEO_DISPLAY_LIST(5, dl_0301B458),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_16000B8C[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(8, geo_switch_anim_state),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(5, dl_0301B500),
            GEO_DISPLAY_LIST(5, dl_0301B518),
            GEO_DISPLAY_LIST(5, dl_0301B530),
            GEO_DISPLAY_LIST(5, dl_0301B548),
            GEO_DISPLAY_LIST(5, dl_0301B560),
            GEO_DISPLAY_LIST(5, dl_0301B578),
            GEO_DISPLAY_LIST(5, dl_0301B590),
            GEO_DISPLAY_LIST(5, dl_0301B5A8),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_17000084[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(5, dl_04022070),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_16000C8C[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(4, dl_0301CDE0),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_1700001C[] = {
    GEO_SWITCH_CASE(1, geo_switch_anim_state),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(4, dl_0401DDE0),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_16000C44[] = {
    GEO_SCALE(0, 0x00004000),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(1, -16, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, dl_0301BFB8),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 97, 0, 0, dl_0301C150),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_16000BEC[] = {
    GEO_SHADOW(1, 155, 50),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, -16, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, dl_0301BFB8),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 97, 0, 0, dl_0301C150),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_17000284[] = {
    GEO_SWITCH_CASE(9, geo_switch_anim_state),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(5, dl_04035300),
        GEO_DISPLAY_LIST(5, dl_04035318),
        GEO_DISPLAY_LIST(5, dl_04035330),
        GEO_DISPLAY_LIST(5, dl_04035348),
        GEO_DISPLAY_LIST(5, dl_04035360),
        GEO_DISPLAY_LIST(5, dl_04035348),
        GEO_DISPLAY_LIST(5, dl_04035330),
        GEO_DISPLAY_LIST(5, dl_04035318),
        GEO_DISPLAY_LIST(5, dl_04035300),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_160000A8[] = {
    GEO_SHADOW(1, 180, 25),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(4, 0, 0, 0, dl_03005408),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(4, 0, 0, 0, dl_030054A0),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_16000000[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_ASM(0, geo_update_layer_transparency),
        GEO_DISPLAY_LIST(5, dl_03000880),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_16000020[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_ASM(0, geo_update_layer_transparency),
        GEO_DISPLAY_LIST(5, dl_03000920),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_16000F98[] = {
    GEO_SHADOW(1, 180, 50),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(4, dl_0302C8A0),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_160001A0[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(8, geo_switch_anim_state),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(4, dl_03007800),
            GEO_DISPLAY_LIST(4, dl_03007800),
            GEO_DISPLAY_LIST(4, dl_03007828),
            GEO_DISPLAY_LIST(4, dl_03007828),
            GEO_DISPLAY_LIST(4, dl_03007850),
            GEO_DISPLAY_LIST(4, dl_03007850),
            GEO_DISPLAY_LIST(4, dl_03007878),
            GEO_DISPLAY_LIST(4, dl_03007878),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_16000200[] = {
    GEO_SHADOW(1, 180, 80),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(8, geo_switch_anim_state),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(4, dl_030078A0),
            GEO_DISPLAY_LIST(4, dl_030078A0),
            GEO_DISPLAY_LIST(4, dl_030078C8),
            GEO_DISPLAY_LIST(4, dl_030078C8),
            GEO_DISPLAY_LIST(4, dl_030078F0),
            GEO_DISPLAY_LIST(4, dl_030078F0),
            GEO_DISPLAY_LIST(4, dl_03007918),
            GEO_DISPLAY_LIST(4, dl_03007918),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_16000264[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(8, geo_switch_anim_state),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(4, dl_030078A0),
            GEO_DISPLAY_LIST(4, dl_030078A0),
            GEO_DISPLAY_LIST(4, dl_030078C8),
            GEO_DISPLAY_LIST(4, dl_030078C8),
            GEO_DISPLAY_LIST(4, dl_030078F0),
            GEO_DISPLAY_LIST(4, dl_030078F0),
            GEO_DISPLAY_LIST(4, dl_03007918),
            GEO_DISPLAY_LIST(4, dl_03007918),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_16000DA8[] = {
    GEO_SHADOW(0, 180, 75),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ASM(10, geo_update_layer_transparency),
            GEO_SWITCH_CASE(2, geo_switch_anim_state),
            GEO_OPEN_NODE(),
                GEO_NODE_START(),
                GEO_OPEN_NODE(),
                    GEO_DISPLAY_LIST(1, dl_03022FF8),
                    GEO_DISPLAY_LIST(4, dl_03023108),
                    GEO_CLOSE_NODE(),
                GEO_NODE_START(),
                GEO_OPEN_NODE(),
                    GEO_DISPLAY_LIST(5, dl_03023298),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_16000CF0[] = {
    GEO_SHADOW(0, 180, 75),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ASM(10, geo_update_layer_transparency),
            GEO_SWITCH_CASE(2, geo_switch_anim_state),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(1, dl_03022FF8),
                GEO_DISPLAY_LIST(5, dl_03022FF8),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_16000D3C[] = {
    GEO_SHADOW(0, 180, 75),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ASM(10, geo_update_layer_transparency),
            GEO_SWITCH_CASE(2, geo_switch_anim_state),
            GEO_OPEN_NODE(),
                GEO_NODE_START(),
                GEO_OPEN_NODE(),
                    GEO_DISPLAY_LIST(1, dl_03022F48),
                    GEO_DISPLAY_LIST(4, dl_030230B0),
                    GEO_CLOSE_NODE(),
                GEO_NODE_START(),
                GEO_OPEN_NODE(),
                    GEO_DISPLAY_LIST(5, dl_03023160),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_16000CA4[] = {
    GEO_SHADOW(0, 180, 75),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ASM(10, geo_update_layer_transparency),
            GEO_SWITCH_CASE(2, geo_switch_anim_state),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(1, dl_03022F48),
                GEO_DISPLAY_LIST(5, dl_03022F48),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_16000AB0[] = {
    GEO_SCALE(0, 0x00004000),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ASM(0, NULL),
                GEO_SCALE(0, 0x00010000),
                GEO_OPEN_NODE(),
                    GEO_DISPLAY_LIST(1, dl_030161F8),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_16000A84[] = {
    GEO_SHADOW(1, 155, 300),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00010000),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, dl_030161F8),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_16000B10[] = {
    GEO_SHADOW(1, 80, 20),
    GEO_OPEN_NODE(),
        GEO_BRANCH_AND_LINK(geo_16000B2C),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_16000E84[] = {
    GEO_SHADOW(1, 180, 80),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(4, dl_0302A660),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_160002C4[] = {
    GEO_SHADOW(1, 180, 80),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(8, geo_switch_anim_state),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(4, dl_03007940),
            GEO_DISPLAY_LIST(4, dl_03007940),
            GEO_DISPLAY_LIST(4, dl_03007968),
            GEO_DISPLAY_LIST(4, dl_03007968),
            GEO_DISPLAY_LIST(4, dl_03007990),
            GEO_DISPLAY_LIST(4, dl_03007990),
            GEO_DISPLAY_LIST(4, dl_030079B8),
            GEO_DISPLAY_LIST(4, dl_030079B8),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_16000328[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(8, geo_switch_anim_state),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(4, dl_03007940),
            GEO_DISPLAY_LIST(4, dl_03007940),
            GEO_DISPLAY_LIST(4, dl_03007968),
            GEO_DISPLAY_LIST(4, dl_03007968),
            GEO_DISPLAY_LIST(4, dl_03007990),
            GEO_DISPLAY_LIST(4, dl_03007990),
            GEO_DISPLAY_LIST(4, dl_030079B8),
            GEO_DISPLAY_LIST(4, dl_030079B8),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_16000E14[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(10, geo_switch_anim_state),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(4, dl_02011ED8),
            GEO_DISPLAY_LIST(4, dl_02011F08),
            GEO_DISPLAY_LIST(4, dl_02011F38),
            GEO_DISPLAY_LIST(4, dl_02011F68),
            GEO_DISPLAY_LIST(4, dl_02011F98),
            GEO_DISPLAY_LIST(4, dl_02011FC8),
            GEO_DISPLAY_LIST(4, dl_02011FF8),
            GEO_DISPLAY_LIST(4, dl_02012028),
            GEO_DISPLAY_LIST(4, dl_02012058),
            GEO_DISPLAY_LIST(4, dl_02012088),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_16000040[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(9, geo_switch_anim_state),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(5, dl_03004298),
            GEO_DISPLAY_LIST(5, dl_03004298),
            GEO_DISPLAY_LIST(5, dl_030042B0),
            GEO_DISPLAY_LIST(5, dl_030042B0),
            GEO_DISPLAY_LIST(5, dl_030042C8),
            GEO_DISPLAY_LIST(5, dl_030042E0),
            GEO_DISPLAY_LIST(5, dl_030042F8),
            GEO_DISPLAY_LIST(5, dl_03004310),
            GEO_DISPLAY_LIST(5, dl_03004328),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_16000ED4[] = {
    GEO_CULLING_RADIUS(300),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(6, geo_switch_anim_state),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, dl_0302C378),
            GEO_DISPLAY_LIST(1, dl_0302C3B0),
            GEO_DISPLAY_LIST(1, dl_0302C3E8),
            GEO_DISPLAY_LIST(4, dl_0302C028),
            GEO_DISPLAY_LIST(1, dl_0302C420),
            GEO_DISPLAY_LIST(1, dl_0302C458),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_16000F24[] = {
    GEO_CULLING_RADIUS(300),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(5, geo_switch_anim_state),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, dl_0302C298),
            GEO_DISPLAY_LIST(1, dl_0302C2B8),
            GEO_DISPLAY_LIST(1, dl_0302C2D8),
            GEO_DISPLAY_LIST(1, dl_0302C2F8),
            GEO_DISPLAY_LIST(1, dl_0302C318),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_0301DBF8[] = {
    GEO_SHADOW(10, 180, 118),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x0000F400),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, dl_04072150),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_030212F4[] = {
    GEO_SHADOW(10, 0, 262),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(1, 0, 0, 0, dl_0406FFC0),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_030225E4[] = {
    GEO_SHADOW(10, 0, 262),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00010000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 138, 0, dl_030222D4),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_0405FE00[] = {
    GEO_SWITCH_CASE(4, geo_switch_anim_state),
    GEO_OPEN_NODE(),
        GEO_NODE_START(),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, dl_04060B70),
            GEO_CLOSE_NODE(),
        GEO_NODE_START(),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, dl_04065C70),
            GEO_TRANSLATE_ROTATE_WITH_DL(1, 0, 0, 0, 0, 45, 0, dl_040679E0),
            GEO_CLOSE_NODE(),
        GEO_NODE_START(),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, dl_04061B70),
            GEO_CLOSE_NODE(),
        GEO_NODE_START(),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, dl_04065C70),
            GEO_TRANSLATE_ROTATE_WITH_DL(1, 0, 0, 0, 0, 45, 0, dl_040691D0),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_0302272C[] = {
    GEO_SHADOW(10, 180, 128),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(0, dl_005F1710),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_03022708[] = {
    GEO_SWITCH_CASE(2, geo_switch_anim_state),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, dl_04063360),
        GEO_DISPLAY_LIST(1, dl_040643E0),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_04075550[] = {
    GEO_CULLING_RADIUS(4000),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(3, geo_switch_anim_state),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, dl_040751E0),
            GEO_DISPLAY_LIST(1, dl_04076240),
            GEO_DISPLAY_LIST(1, dl_04077040),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout geo_00603670[] = {
};


const GeoLayout area_2_geo_14000408[] = {
    GEO_NODE_SCREEN_AREA(10, 160, 120, 160, 120),
    GEO_OPEN_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_NODE_ORTHO(100),
            GEO_OPEN_NODE(),
                GEO_BACKGROUND_COLOR(0xFFFF),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_ZBUFFER(1),
        GEO_OPEN_NODE(),
            GEO_CAMERA_FRUSTUM(45, 100, 25000),
            GEO_OPEN_NODE(),
                GEO_CAMERA(0, 0, 0, 1000, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_RENDER_OBJ(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_ASM(0, NULL),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout area_1_geo_14000414[] = {
    GEO_NODE_SCREEN_AREA(0, 160, 120, 160, 120),
    GEO_OPEN_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_NODE_ORTHO(100),
            GEO_OPEN_NODE(),
                GEO_ASM(0, NULL),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_ZBUFFER(1),
        GEO_OPEN_NODE(),
            GEO_CAMERA_FRUSTUM(45, 128, 16384),
            GEO_OPEN_NODE(),
                GEO_CAMERA(0, 0, 0, 1200, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_TRANSLATE_NODE_WITH_DL(1, 300, 0, 1792, area_1_dl_07000858),
                    GEO_TRANSLATE_NODE_WITH_DL(1, 300, 0, 1792, area_1_dl_07001100),
                    GEO_TRANSLATE_NODE_WITH_DL(1, 300, 0, 1792, area_1_dl_07001BA0),
                    GEO_TRANSLATE_NODE_WITH_DL(1, 300, 0, 1792, area_1_dl_070025F0),
                    GEO_TRANSLATE_NODE_WITH_DL(1, 300, 0, 1792, area_1_dl_07003258),
                    GEO_TRANSLATE_NODE_WITH_DL(1, 100, 0, 1792, area_1_dl_07003DB8),
                    GEO_TRANSLATE_NODE_WITH_DL(1, 100, 0, 1792, area_1_dl_070048C8),
                    GEO_TRANSLATE_NODE_WITH_DL(1, 100, 0, 1792, area_1_dl_07005558),
                    GEO_TRANSLATE_NODE_WITH_DL(1, 100, 0, 1792, area_1_dl_070059F8),
                    GEO_TRANSLATE_NODE_WITH_DL(1, 100, 0, 1792, area_1_dl_070063B0),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};
