const GeoLayout wdw_area_1_geo_19001700[] = {
    GEO_NODE_SCREEN_AREA(10, 160, 120, 160, 120),
    GEO_OPEN_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_NODE_ORTHO(100),
            GEO_OPEN_NODE(),
                GEO_BACKGROUND(0x0000, geo_skybox_main),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_ZBUFFER(1),
        GEO_OPEN_NODE(),
            GEO_CAMERA_FRUSTUM_WITH_FUNC(45, 100, 32767, geo_camera_fov),
            GEO_OPEN_NODE(),
                GEO_CAMERA(1, 0, 2000, 6000, 3072, 0, -4608, geo_camera_main),
                GEO_OPEN_NODE(),
                    GEO_DISPLAY_LIST(1, wdw_area_1_dl_0E0C4A10),
                    GEO_DISPLAY_LIST(4, wdw_area_1_dl_0E0E9188),
                    GEO_DISPLAY_LIST(5, wdw_area_1_dl_0E0EC380),
                    GEO_RENDER_OBJ(),
                    GEO_ASM(0, geo_envfx_main),
                    GEO_ASM(20480, geo_movtex_draw_water_regions),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_cannon_circle_base),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};
