const GeoLayout ssl_geo_0C000610[] = {
    GEO_SHADOW(1, 150, 50),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(2, geo_switch_anim_state),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(4, ssl_dl_050127D8),
            GEO_DISPLAY_LIST(4, ssl_dl_05012808),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout ssl_geo_0C000644[] = {
    GEO_SHADOW(1, 150, 50),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(4, ssl_dl_050130B0),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout ssl_geo_05014630[] = {
    GEO_CULLING_RADIUS(5000),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(5, ssl_dl_050145C0),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout ssl_geo_0C000000[] = {
    GEO_SHADOW(1, 150, 250),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00010000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(4, 0, 0, 0, ssl_dl_050041E8),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 62, 0, 0, ssl_dl_05003F20),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 44, 0, 0, ssl_dl_05003D80),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 58, 0, 0, ssl_dl_05003BD0),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -3, 17, 17, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, ssl_dl_05004330),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 68, 0, 0, ssl_dl_050047C8),
                            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_SWITCH_CASE(4, geo_switch_anim_state),
                                GEO_OPEN_NODE(),
                                    GEO_NODE_START(),
                                    GEO_NODE_START(),
                                    GEO_OPEN_NODE(),
                                        GEO_SCALE(0, 0x00004000),
                                        GEO_OPEN_NODE(),
                                            GEO_ASM(0, geo_offset_klepto_held_object),
                                            GEO_TRANSLATE_ROTATE_WITH_DL(1, 0, 100, 0, 180, 270, 0, dl_03022F48),
                                            GEO_CLOSE_NODE(),
                                        GEO_CLOSE_NODE(),
                                    GEO_NODE_START(),
                                    GEO_OPEN_NODE(),
                                        GEO_SCALE(0, 0x00004000),
                                        GEO_OPEN_NODE(),
                                            GEO_ASM(0, geo_offset_klepto_held_object),
                                            GEO_TRANSLATE_ROTATE_WITH_DL(1, 0, 100, 0, 180, 270, 0, dl_0302B870),
                                            GEO_ASM(0, geo_offset_klepto_held_object),
                                            GEO_TRANSLATE_ROTATE_WITH_DL(4, 0, 100, 0, 180, 270, 0, dl_0302BA18),
                                            GEO_CLOSE_NODE(),
                                        GEO_CLOSE_NODE(),
                                    GEO_NODE_START(),
                                    GEO_OPEN_NODE(),
                                        GEO_SCALE(0, 0x00004000),
                                        GEO_OPEN_NODE(),
                                            GEO_ASM(0, geo_offset_klepto_held_object),
                                            GEO_TRANSLATE_ROTATE_WITH_DL(1, 0, 100, 0, 180, 270, 0, dl_0302C620),
                                            GEO_CLOSE_NODE(),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -3, 17, 65519, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, ssl_dl_05004438),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 68, 0, 0, ssl_dl_05004B58),
                            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 49, 65527, 65519, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(4, 0, 0, 0, ssl_dl_05004D38),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(4, 34, 0, 0, ssl_dl_05004F58),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(4, 79, 0, 0, ssl_dl_05005178),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 49, 65527, 17, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(4, 0, 0, 0, ssl_dl_05004C28),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(4, 34, 0, 0, ssl_dl_05004E48),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(4, 79, 0, 0, ssl_dl_05005068),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, ssl_dl_05004118),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout ssl_geo_0C0002AC[] = {
    GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 447, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, ssl_dl_0500C640),
                GEO_ANIMATED_PART(1, 281, 5, 65117, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 400, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 401, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, ssl_dl_0500BF00),
                                GEO_CLOSE_NODE(),
                            GEO_ANIMATED_PART(1, 0, 0, 0, ssl_dl_0500C100),
                            GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, ssl_dl_0500C378),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(1, 281, 5, 65318, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 400, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 401, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, ssl_dl_0500BF00),
                                GEO_CLOSE_NODE(),
                            GEO_ANIMATED_PART(1, 0, 0, 0, ssl_dl_0500C100),
                            GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, ssl_dl_0500C378),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(1, 281, 5, 65518, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 400, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 401, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, ssl_dl_0500BF00),
                                GEO_CLOSE_NODE(),
                            GEO_ANIMATED_PART(1, 0, 0, 0, ssl_dl_0500C100),
                            GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, ssl_dl_0500C378),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(1, 281, 5, 180, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 400, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 401, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, ssl_dl_0500BF00),
                                GEO_CLOSE_NODE(),
                            GEO_ANIMATED_PART(1, 0, 0, 0, ssl_dl_0500C100),
                            GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, ssl_dl_0500C378),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, ssl_dl_0500C908),
            GEO_OPEN_NODE(),
                GEO_SWITCH_CASE(4, geo_switch_anim_state),
                GEO_OPEN_NODE(),
                    GEO_DISPLAY_LIST(4, ssl_dl_0500C9B8),
                    GEO_DISPLAY_LIST(4, ssl_dl_0500CA50),
                    GEO_DISPLAY_LIST(4, ssl_dl_0500CAE8),
                    GEO_DISPLAY_LIST(4, ssl_dl_0500CB80),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(1, 181, 89, 80, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 199, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, ssl_dl_0500BC88),
                        GEO_ANIMATED_PART(1, 200, 199, 199, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 336, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(1, 0, 0, 0, ssl_dl_0500B748),
                                    GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, ssl_dl_0500B9C0),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout ssl_geo_0C0005A8[] = {
    GEO_SHADOW(11, 180, 300),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, ssl_dl_0500CC18),
            GEO_BRANCH(1, ssl_geo_0C0002AC),
            GEO_DISPLAY_LIST(1, ssl_dl_0500CC30),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout ssl_geo_0C0005E4[] = {
    GEO_SHADOW(11, 180, 300),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_BRANCH(1, ssl_geo_0C0002AC),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout ssl_geo_120005C0[] = {
    GEO_CULLING_RADIUS(2000),
    GEO_OPEN_NODE(),
        GEO_ASM(2049, geo_movtex_draw_colored_2_no_update),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout ssl_geo_120005D8[] = {
    GEO_CULLING_RADIUS(2000),
    GEO_OPEN_NODE(),
        GEO_RENDER_RANGE(-1000, 4000),
        GEO_OPEN_NODE(),
            GEO_ASM(2050, geo_movtex_draw_colored_2_no_update),
            GEO_CLOSE_NODE(),
        GEO_RENDER_RANGE(4000, 12800),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, ssl_dl_07004AE0),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout ssl_geo_12000618[] = {
    GEO_CULLING_RADIUS(1000),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, ssl_dl_0700BF18),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout ssl_geo_12000734[] = {
    GEO_CULLING_RADIUS(700),
    GEO_OPEN_NODE(),
        GEO_SHADOW(11, 180, 550),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, ssl_dl_070220A8),
            GEO_DISPLAY_LIST(4, ssl_dl_070221E8),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout ssl_geo_12000764[] = {
    GEO_CULLING_RADIUS(550),
    GEO_OPEN_NODE(),
        GEO_SHADOW(50, 180, 0),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, ssl_dl_070228A8),
            GEO_DISPLAY_LIST(4, ssl_dl_070229E8),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout ssl_geo_12000794[] = {
    GEO_CULLING_RADIUS(700),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, ssl_dl_07022CF8),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout ssl_geo_120007AC[] = {
    GEO_CULLING_RADIUS(900),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, ssl_dl_070233A8),
        GEO_DISPLAY_LIST(4, ssl_dl_070235C0),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout ssl_geo_12000630[] = {
    GEO_CULLING_RADIUS(4000),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, ssl_dl_0700FCE0),
        GEO_CLOSE_NODE(),
    GEO_END(),
};
