const GeoLayout sl_geo_06003754[] = {
    GEO_SHADOW(1, 200, 70),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00007333),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 75, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 146, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, sl_dl_06002B30),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 65461, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 146, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, sl_dl_06002BC8),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                        GEO_OPEN_NODE(),
                            GEO_DISPLAY_LIST(4, sl_dl_06002D88),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, sl_dl_06002C60),
                    GEO_ANIMATED_PART(4, 0, 0, 0, sl_dl_06003010),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout sl_geo_06003874[] = {
    GEO_SHADOW(1, 200, 210),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x0000E666),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 75, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 146, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, sl_dl_06002B30),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 65461, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 146, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, sl_dl_06002BC8),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                        GEO_OPEN_NODE(),
                            GEO_DISPLAY_LIST(4, sl_dl_06002EF0),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, sl_dl_06002C60),
                    GEO_ANIMATED_PART(4, 0, 0, 0, sl_dl_06003010),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout sl_geo_0D000000[] = {
    GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(1, 0, 0, 0, sl_dl_06005750),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 65416, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, sl_dl_06005980),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 120, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, sl_dl_060059F0),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(1, 0, 0, 0, sl_dl_06005688),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout sl_geo_0D000078[] = {
    GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(5, 0, 0, 0, sl_dl_06005750),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 65416, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(5, 0, 0, 0, sl_dl_06005980),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 120, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(5, 0, 0, 0, sl_dl_060059F0),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_ANIMATED_PART(5, 0, 0, 0, sl_dl_06005688),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout sl_geo_0D0000F0[] = {
    GEO_SHADOW(1, 200, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_update_layer_transparency),
            GEO_SWITCH_CASE(2, geo_switch_anim_state),
            GEO_OPEN_NODE(),
                GEO_BRANCH(1, sl_geo_0D000000),
                GEO_BRANCH(1, sl_geo_0D000078),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout sl_geo_12000390[] = {
    GEO_CULLING_RADIUS(350),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, sl_dl_0700A780),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout sl_geo_12000360[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(5, sl_dl_0700A890),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout sl_geo_12000378[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(5, sl_dl_0700A980),
        GEO_CLOSE_NODE(),
    GEO_END(),
};
