const GeoLayout wdw_geo_0C000264[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_SHADOW(10, 150, 400),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, wdw_dl_0500E8A8),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout wdw_geo_0C000000[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(4, wdw_dl_050008C8),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout wdw_geo_0C000018[] = {
    GEO_SHADOW(1, 255, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 147, 65531, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, wdw_dl_05004D48),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 96, 0, 0, wdw_dl_05001DF0),
                    GEO_ANIMATED_PART(1, 34, 65501, 31, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(4, 0, 0, 0, wdw_dl_05003728),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(4, 91, 0, 0, wdw_dl_050034D8),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(4, 121, 0, 0, wdw_dl_050033B0),
                                GEO_ANIMATED_PART(1, 121, 0, 0, NULL),
                                GEO_CLOSE_NODE(),
                            GEO_ANIMATED_PART(1, 91, 0, 0, NULL),
                            GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(4, 0, 0, 0, wdw_dl_05003600),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -31, 5, 37, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, wdw_dl_05004A98),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 42, 0, 0, wdw_dl_05004928),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -31, 5, 65499, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, wdw_dl_05004CA8),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 42, 0, 0, wdw_dl_05004B38),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 34, 65501, 65505, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(4, 0, 0, 0, wdw_dl_05003288),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(4, 91, 0, 0, wdw_dl_05003038),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(4, 121, 0, 0, wdw_dl_05002F10),
                                GEO_ANIMATED_PART(1, 121, 0, 0, NULL),
                                GEO_CLOSE_NODE(),
                            GEO_ANIMATED_PART(1, 91, 0, 0, NULL),
                            GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(4, 0, 0, 0, wdw_dl_05003160),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout wdw_geo_0C0001E4[] = {
    GEO_SCALE(0, 0x00004000),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(8, geo_switch_anim_state),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(4, wdw_dl_050098C8),
            GEO_DISPLAY_LIST(4, wdw_dl_050098B0),
            GEO_DISPLAY_LIST(4, wdw_dl_05009898),
            GEO_DISPLAY_LIST(4, wdw_dl_05009880),
            GEO_DISPLAY_LIST(4, wdw_dl_05009868),
            GEO_DISPLAY_LIST(4, wdw_dl_05009850),
            GEO_DISPLAY_LIST(4, wdw_dl_05009838),
            GEO_DISPLAY_LIST(4, wdw_dl_05009820),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout wdw_geo_0C000248[] = {
    GEO_SHADOW(11, 180, 300),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, wdw_dl_0500B750),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout wdw_geo_0C00028C[] = {
    GEO_SHADOW(1, 200, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, wdw_dl_05014D80),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 140, 65525, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, wdw_dl_05011EC0),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 150, 50, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, wdw_dl_05014560),
                                GEO_ANIMATED_PART(4, 0, 0, 0, wdw_dl_050127F8),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 135, 0, 65452, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(4, wdw_dl_050126E8),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 168, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                                GEO_OPEN_NODE(),
                                    GEO_DISPLAY_LIST(4, wdw_dl_050126E8),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_ANIMATED_PART(1, 168, 0, 0, NULL),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 149, 65508, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, wdw_dl_050125F8),
                        GEO_ANIMATED_PART(1, 0, 0, 0, wdw_dl_05012148),
                        GEO_ANIMATED_PART(1, 0, 0, 0, wdw_dl_050123A8),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                    GEO_OPEN_NODE(),
                        GEO_DISPLAY_LIST(4, wdw_dl_050126E8),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout wdw_geo_0D00038C[] = {
    GEO_SCALE(0, 0x00004000),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(1, -13, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, wdw_dl_06011B28),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 135, 0, 0, wdw_dl_06011CF0),
                GEO_ANIMATED_PART(1, -33, 65450, 65501, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, wdw_dl_06011E48),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(1, -34, 71, 65500, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, wdw_dl_06011FA0),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout wdw_geo_0D000450[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, wdw_dl_06016F90),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout wdw_geo_0D000468[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, wdw_dl_060178C0),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout wdw_geo_0D000324[] = {
    GEO_SCALE(0, 0x00004000),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, wdw_dl_0600DDD8),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 160, 0, 0, wdw_dl_0600E038),
                GEO_ANIMATED_PART(1, 32, 112, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, wdw_dl_0600DED8),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout wdw_geo_0D000414[] = {
    GEO_SCALE(0, 0x00008000),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_update_layer_transparency),
            GEO_ANIMATED_PART(5, 0, 0, 0, wdw_dl_06013AC0),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout wdw_geo_0D0002F4[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, wdw_dl_0600D3F8),
        GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(4, wdw_dl_0600D268),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout wdw_geo_0D000284[] = {
    GEO_SCALE(0, 0x00004000),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(4, 0, 0, 0, wdw_dl_0600A180),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(4, 238, 0, 0, wdw_dl_0600A088),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(4, 317, 0, 0, wdw_dl_06009F90),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(4, 314, 0, 0, wdw_dl_06009E98),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout wdw_geo_0D000000[] = {
    GEO_SHADOW(1, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                    GEO_OPEN_NODE(),
                        GEO_DISPLAY_LIST(4, wdw_dl_06000A08),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 100, 65461, 65431, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, wdw_dl_06004070),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 405, 0, 0, wdw_dl_06004040),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 540, 0, 0, wdw_dl_06000EC0),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -40, 65461, 65411, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, wdw_dl_06004120),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 405, 0, 0, wdw_dl_060040F0),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 540, 0, 0, wdw_dl_06000EC0),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -40, 65461, 125, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, wdw_dl_060041D0),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 405, 0, 0, wdw_dl_060041A0),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 540, 0, 0, wdw_dl_06000EC0),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -150, 65449, 111, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(4, wdw_dl_06000BD8),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(4, 0, 0, 0, wdw_dl_06000CA8),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -150, 65449, 65425, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(4, 0, 0, 0, wdw_dl_06000D78),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(4, wdw_dl_06000BD8),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 100, 65461, 95, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, wdw_dl_06004648),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 405, 0, 0, wdw_dl_06004618),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 540, 0, 0, wdw_dl_06000EC0),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 147, 84, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, wdw_dl_06005328),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 216, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                                GEO_OPEN_NODE(),
                                    GEO_DISPLAY_LIST(4, wdw_dl_06000AF0),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_ANIMATED_PART(1, 216, 0, 0, NULL),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout wdw_geo_12000580[] = {
    GEO_CULLING_RADIUS(550),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, wdw_dl_07012B90),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout wdw_geo_12000598[] = {
    GEO_CULLING_RADIUS(350),
    GEO_OPEN_NODE(),
        GEO_SHADOW(12, 150, 110),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, wdw_dl_07012E88),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout wdw_geo_120005C0[] = {
    GEO_CULLING_RADIUS(200),
    GEO_OPEN_NODE(),
        GEO_SHADOW(11, 150, 90),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(5, wdw_dl_070131B8),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout wdw_geo_120005E8[] = {
    GEO_CULLING_RADIUS(420),
    GEO_OPEN_NODE(),
        GEO_SHADOW(12, 150, 240),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, wdw_dl_07013490),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout wdw_geo_12000610[] = {
    GEO_CULLING_RADIUS(800),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, wdw_dl_07013B70),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout wdw_geo_12000628[] = {
    GEO_CULLING_RADIUS(900),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, wdw_dl_07013E40),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout wdw_geo_12000640[] = {
    GEO_CULLING_RADIUS(450),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, wdw_dl_070140E0),
        GEO_CLOSE_NODE(),
    GEO_END(),
};
