GeoLayout exclamation_box_geo[] = {
    GEO_CULLING_RADIUS(300),
    GEO_OPEN_NODE(),
        GEO_SHADOW(SHADOW_SQUARE_PERMANENT, 180, 70),
        GEO_OPEN_NODE(),
            GEO_SWITCH_CASE(14, geo_switch_anim_state),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, exclamation_box_seg8_dl_08019318),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, exclamation_box_seg8_dl_08019378),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, exclamation_box_seg8_dl_080193D8),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, exclamation_box_seg8_dl_08019438),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, exclamation_box_seg8_dl_04037000),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, exclamation_box_seg8_dl_04037100),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, exclamation_box_seg8_dl_04037200),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, exclamation_box_seg8_dl_04037300),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, exclamation_box_seg8_dl_04037400),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, exclamation_box_seg8_dl_04037500),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, exclamation_box_seg8_dl_04037600),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, exclamation_box_seg8_dl_04037700),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, exclamation_box_seg8_dl_04037800),
                GEO_DISPLAY_LIST(LAYER_OPAQUE, exclamation_box_seg8_dl_04037900),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};
