const GeoLayout bob_geo_0C000308[] = {
    GEO_CULLING_RADIUS(150),
    GEO_OPEN_NODE(),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(5, bob_dl_05011000),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bob_geo_0C000328[] = {
    GEO_CULLING_RADIUS(150),
    GEO_OPEN_NODE(),
        GEO_SHADOW(1, 100, 160),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bob_geo_0C000000[] = {
    GEO_SHADOW(1, 150, 300),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                        GEO_OPEN_NODE(),
                            GEO_DISPLAY_LIST(4, bob_dl_0500B188),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 0, 65293, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 488, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 110, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(1, 0, 0, 0, bob_dl_0500AD08),
                                    GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(4, bob_dl_0500A5D8),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(4, 0, 0, 0, bob_dl_0500B2D0),
                    GEO_ANIMATED_PART(1, 0, 0, 0, bob_dl_0500B418),
                    GEO_ANIMATED_PART(1, 0, 0, 0, bob_dl_0500B6C0),
                    GEO_ANIMATED_PART(1, 0, 243, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 488, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 110, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(1, 0, 0, 0, bob_dl_0500B068),
                                    GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(4, bob_dl_0500A890),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 0, 65535, 36, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 548, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(4, bob_dl_0500A4F0),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(1, 189, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                                    GEO_OPEN_NODE(),
                                        GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                                        GEO_OPEN_NODE(),
                                            GEO_DISPLAY_LIST(4, bob_dl_0500A6C0),
                                            GEO_CLOSE_NODE(),
                                        GEO_CLOSE_NODE(),
                                    GEO_ASM(0, geo_update_projectile_pos_from_parent),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 0, 1, 36, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 548, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(4, bob_dl_0500A7A8),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(1, 189, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                                    GEO_OPEN_NODE(),
                                        GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                                        GEO_OPEN_NODE(),
                                            GEO_DISPLAY_LIST(4, bob_dl_0500A978),
                                            GEO_CLOSE_NODE(),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bob_geo_0D000358[] = {
    GEO_SHADOW(1, 155, 200),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 14, 3, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, bob_dl_06015850),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 46, 0, 0, bob_dl_06016F20),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 154, 0, 0, bob_dl_06016D98),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 153, 0, 0, bob_dl_06016C10),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 236, 42, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(1, 0, 0, 0, bob_dl_060160B0),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(4, bob_dl_06016120),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(1, 217, 65534, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(1, 0, 0, 0, bob_dl_060169E8),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(4, bob_dl_06016A78),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(1, 49, 0, 65502, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(4, 0, 0, 0, bob_dl_06015480),
                            GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(1, 49, 0, 37, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(4, 0, 0, 0, bob_dl_06015578),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bob_geo_0D000480[] = {
    GEO_CULLING_RADIUS(2000),
    GEO_OPEN_NODE(),
        GEO_TRANSLATE_NODE(0, 0, 65486, 0),
        GEO_OPEN_NODE(),
            GEO_SHADOW(51, 180, 0),
            GEO_OPEN_NODE(),
                GEO_SCALE(0, 0x00004000),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bob_dl_0601F5E0),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, -12, 490, 65531, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, bob_dl_0601FEA8),
                                GEO_CLOSE_NODE(),
                            GEO_ANIMATED_PART(1, -18, 65057, 65531, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, bob_dl_06020038),
                                GEO_CLOSE_NODE(),
                            GEO_ANIMATED_PART(1, 1075, 570, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, bob_dl_0601F880),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(4, 400, 0, 0, NULL),
                                    GEO_OPEN_NODE(),
                                        GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                                        GEO_OPEN_NODE(),
                                            GEO_DISPLAY_LIST(4, bob_dl_0601FBC0),
                                            GEO_CLOSE_NODE(),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_ANIMATED_PART(1, 1068, 64962, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, bob_dl_0601FAE8),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(4, 400, 0, 0, NULL),
                                    GEO_OPEN_NODE(),
                                        GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                                        GEO_OPEN_NODE(),
                                            GEO_DISPLAY_LIST(4, bob_dl_0601FCA8),
                                            GEO_CLOSE_NODE(),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bob_geo_0D000214[] = {
    GEO_SHADOW(1, 155, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, bob_dl_06008250),
                GEO_OPEN_NODE(),
                    GEO_SWITCH_CASE(2, geo_switch_anim_state),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 114, 0, 0, bob_dl_06007AF8),
                        GEO_ANIMATED_PART(1, 114, 0, 0, bob_dl_06007B20),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -29, 39, 60, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bob_dl_0600B838),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 60, 0, 0, bob_dl_060086D0),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -29, 39, 65476, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bob_dl_0600BA10),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 60, 0, 0, bob_dl_06008B50),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 55, 25, 65463, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bob_dl_0600BC18),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 54, 0, 0, bob_dl_0600BA90),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 55, 25, 74, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bob_dl_0600BE10),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 54, 0, 0, bob_dl_0600BC88),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bob_geo_0D0000D0[] = {
    GEO_SHADOW(1, 155, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, bob_dl_0600C498),
                GEO_OPEN_NODE(),
                    GEO_SWITCH_CASE(2, geo_switch_anim_state),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 114, 0, 0, bob_dl_06007AF8),
                        GEO_ANIMATED_PART(1, 114, 0, 0, bob_dl_06007B20),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -29, 39, 60, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bob_dl_0600B838),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 60, 0, 0, bob_dl_060086D0),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -29, 39, 65476, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bob_dl_0600BA10),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 60, 0, 0, bob_dl_06008B50),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 55, 25, 65463, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bob_dl_0600BC18),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 54, 0, 0, bob_dl_0600BA90),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 55, 25, 74, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bob_dl_0600BE10),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 54, 0, 0, bob_dl_0600BC88),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bob_geo_0D0005D0[] = {
    GEO_SHADOW(1, 150, 60),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(4, bob_dl_060212E8),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bob_geo_0D0005EC[] = {
    GEO_SHADOW(1, 150, 200),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, bob_dl_06024940),
                GEO_ANIMATED_PART(1, 0, 0, 0, bob_dl_06024FC0),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, bob_dl_06024240),
                GEO_ANIMATED_PART(1, 0, 0, 0, bob_dl_06024D60),
                GEO_ANIMATED_PART(4, 0, 0, 0, bob_dl_06024B00),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bob_geo_0D000000[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, bob_dl_06000A08),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 2040, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bob_dl_06000B08),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 460, 0, 0, bob_dl_06000BF8),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 460, 0, 0, bob_dl_06000CE0),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(1, 344, 0, 0, bob_dl_06000DB0),
                                    GEO_OPEN_NODE(),
                                        GEO_ANIMATED_PART(1, 288, 0, 0, bob_dl_06000E38),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bob_geo_0D0000B8[] = {
    GEO_CULLING_RADIUS(450),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, bob_dl_06002410),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bob_geo_12000440[] = {
    GEO_CULLING_RADIUS(1000),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(4, bob_dl_0700E458),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bob_geo_12000458[] = {
    GEO_CULLING_RADIUS(1200),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, bob_dl_0700E768),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bob_geo_12000470[] = {
    GEO_CULLING_RADIUS(800),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(4, bob_dl_0700E8A0),
        GEO_CLOSE_NODE(),
    GEO_END(),
};
