const GeoLayout hmc_geo_0C000000[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, hmc_dl_050044B0),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 116, 0, 0, hmc_dl_05004C00),
                    GEO_ANIMATED_PART(4, 116, 0, 0, hmc_dl_05004D30),
                    GEO_ANIMATED_PART(1, -68, 65531, 65496, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, hmc_dl_05003C48),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -68, 65531, 40, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, hmc_dl_05003518),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 80, 1, 78, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, hmc_dl_050032A0),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 80, 0, 0, hmc_dl_05003820),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 80, 1, 65458, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, hmc_dl_050039D0),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 80, 0, 0, hmc_dl_05003F50),
                            GEO_ASM(0, geo_update_projectile_pos_from_parent),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout hmc_geo_0C000110[] = {
    GEO_SHADOW(1, 150, 80),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, hmc_dl_0500B820),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 99, 65525, NULL),
                GEO_OPEN_NODE(),
                    GEO_SWITCH_CASE(4, geo_switch_anim_state),
                    GEO_OPEN_NODE(),
                        GEO_NODE_START(),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 0, 0, 0, hmc_dl_0500B2E8),
                            GEO_CLOSE_NODE(),
                        GEO_NODE_START(),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 0, 0, 0, hmc_dl_0500B310),
                            GEO_CLOSE_NODE(),
                        GEO_NODE_START(),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 0, 0, 0, hmc_dl_0500B2E8),
                            GEO_OPEN_NODE(),
                                GEO_TRANSLATE_ROTATE_WITH_DL(1, 100, 0, 0, 65446, 65446, 0, dl_03022F48),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_NODE_START(),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 0, 0, 0, hmc_dl_0500B310),
                            GEO_OPEN_NODE(),
                                GEO_TRANSLATE_ROTATE_WITH_DL(1, 100, 0, 0, 65446, 65446, 0, dl_03022F48),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(1, 71, 69, 65527, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, hmc_dl_0500B988),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 86, 0, 0, hmc_dl_0500BB28),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 64, 0, 0, hmc_dl_0500CF68),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(1, -71, 68, 65527, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, hmc_dl_0500BC78),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 86, 0, 0, hmc_dl_0500BE38),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 64, 0, 0, hmc_dl_0500CFF0),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(1, 43, 65514, 65535, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, hmc_dl_0500BFF8),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 46, 0, 0, hmc_dl_0500C1B8),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 36, 0, 0, hmc_dl_0500D078),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(1, -43, 65514, 65535, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, hmc_dl_0500C368),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 46, 0, 0, hmc_dl_0500C528),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 36, 0, 0, hmc_dl_0500D108),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(1, 0, 65521, 65479, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, hmc_dl_0500C6E8),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 45, 0, 0, hmc_dl_0500C898),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 46, 0, 0, hmc_dl_0500CA48),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout hmc_geo_0C00036C[] = {
    GEO_CULLING_RADIUS(200),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(5, hmc_dl_05016040),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout hmc_geo_160004D0[] = {
    GEO_TRANSLATE_NODE(0, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, -300, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_OPEN_NODE(),
                    GEO_RENDER_RANGE(-2048, 3500),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, hmc_dl_03014A80),
                        GEO_CLOSE_NODE(),
                    GEO_RENDER_RANGE(3500, 32767),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, hmc_dl_03014F98),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout hmc_geo_120005A0[] = {
    GEO_CULLING_RADIUS(550),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, hmc_dl_07022DA0),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout hmc_geo_120005B8[] = {
    GEO_CULLING_RADIUS(200),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, hmc_dl_07023090),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout hmc_geo_120005D0[] = {
    GEO_CULLING_RADIUS(500),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, hmc_dl_07022AA0),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout hmc_geo_12000548[] = {
    GEO_CULLING_RADIUS(300),
    GEO_OPEN_NODE(),
        GEO_SHADOW(0, 180, 400),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, hmc_dl_07023BC8),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout hmc_geo_12000570[] = {
    GEO_CULLING_RADIUS(150),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, hmc_dl_07023E10),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout hmc_geo_12000588[] = {
    GEO_CULLING_RADIUS(100),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, hmc_dl_07024110),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout hmc_geo_12000530[] = {
    GEO_CULLING_RADIUS(1000),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(4, hmc_dl_0701FFF8),
        GEO_CLOSE_NODE(),
    GEO_END(),
};
