const GeoLayout castle_grounds_area_1_geo_19000000[] = {
    GEO_NODE_SCREEN_AREA(10, 160, 120, 160, 120),
    GEO_OPEN_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_NODE_ORTHO(100),
            GEO_OPEN_NODE(),
                GEO_BACKGROUND(castle_grounds_skybox_ptrlist, geo_skybox_main),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_ZBUFFER(1),
        GEO_OPEN_NODE(),
            GEO_CAMERA_FRUSTUM_WITH_FUNC(45, 100, 32767, geo_camera_fov),
            GEO_OPEN_NODE(),
                GEO_CAMERA(1, 0, 2000, 6000, 3072, 0, -4608, geo_camera_main),
                GEO_OPEN_NODE(),
                    GEO_DISPLAY_LIST(1, castle_grounds_area_1_dl_0E0C8930),
                    GEO_DISPLAY_LIST(4, castle_grounds_area_1_dl_0E0E4ED0),
                    GEO_DISPLAY_LIST(5, castle_grounds_area_1_dl_0E0E7680),
                    GEO_RENDER_OBJ(),
                    GEO_ASM(0, geo_envfx_main),
                    GEO_ASM(20480, geo_movtex_draw_water_regions),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_cannon_circle_base),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout castle_grounds_area_1_area_2_geo_190000C0[] = {
    GEO_NODE_SCREEN_AREA(10, 160, 120, 160, 120),
    GEO_OPEN_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_NODE_ORTHO(100),
            GEO_OPEN_NODE(),
                GEO_BACKGROUND_COLOR(0x0000),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_ZBUFFER(1),
        GEO_OPEN_NODE(),
            GEO_CAMERA_FRUSTUM_WITH_FUNC(45, 100, 32767, geo_camera_fov),
            GEO_OPEN_NODE(),
                GEO_CAMERA(1, 0, 2000, 6000, 3072, 0, -4608, geo_camera_main),
                GEO_OPEN_NODE(),
                    GEO_DISPLAY_LIST(1, castle_grounds_area_1_area_2_dl_0E106D50),
                    GEO_DISPLAY_LIST(4, castle_grounds_area_1_area_2_dl_0E108600),
                    GEO_DISPLAY_LIST(5, castle_grounds_area_1_area_2_dl_0E108780),
                    GEO_RENDER_OBJ(),
                    GEO_ASM(0, geo_envfx_main),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_cannon_circle_base),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout castle_grounds_area_1_area_2_area_3_geo_19000170[] = {
    GEO_NODE_SCREEN_AREA(10, 160, 120, 160, 120),
    GEO_OPEN_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_NODE_ORTHO(100),
            GEO_OPEN_NODE(),
                GEO_BACKGROUND_COLOR(0x0000),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_ZBUFFER(1),
        GEO_OPEN_NODE(),
            GEO_CAMERA_FRUSTUM_WITH_FUNC(45, 100, 32767, geo_camera_fov),
            GEO_OPEN_NODE(),
                GEO_CAMERA(1, 0, 2000, 6000, 3072, 0, -4608, geo_camera_main),
                GEO_OPEN_NODE(),
                    GEO_DISPLAY_LIST(1, castle_grounds_area_1_area_2_area_3_dl_0E1248F0),
                    GEO_DISPLAY_LIST(4, castle_grounds_area_1_area_2_area_3_dl_0E128900),
                    GEO_DISPLAY_LIST(5, castle_grounds_area_1_area_2_area_3_dl_0E129610),
                    GEO_RENDER_OBJ(),
                    GEO_ASM(0, geo_envfx_main),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_ZBUFFER(0),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_cannon_circle_base),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};
