GeoLayout piranha_plant_geo[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 155, 200),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x4000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 14, 3, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, DL_piranha_plant_geo_0x6015850),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 46, 0, 0, DL_piranha_plant_geo_0x6016f20),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 154, 0, 0, DL_piranha_plant_geo_0x6016d98),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 153, 0, 0, DL_piranha_plant_geo_0x6016c10),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 236, 42, 0, 0),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, DL_piranha_plant_geo_0x60160b0),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(LAYER_ALPHA, DL_piranha_plant_geo_0x6016120),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 217, -2, 0, 0),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, DL_piranha_plant_geo_0x60169e8),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(LAYER_ALPHA, DL_piranha_plant_geo_0x6016a78),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 49, 0, -34, 0),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, DL_piranha_plant_geo_0x6015480),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 49, 0, 37, 0),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, DL_piranha_plant_geo_0x6015578),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};

