const GeoLayout castle_inside_geo_0C000000[] = {
    GEO_SHADOW(1, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, castle_inside_dl_05000670),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 1, 65524, 37, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, castle_inside_dl_05000528),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 1, 65524, 65499, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, castle_inside_dl_05000600),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, castle_inside_dl_05000598),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout castle_inside_geo_0C000098[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, castle_inside_dl_05007230),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 78, 0, 0, castle_inside_dl_05006A18),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 132, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_SWITCH_CASE(8, NULL),
                        GEO_OPEN_NODE(),
                            GEO_DISPLAY_LIST(1, castle_inside_dl_05005CE0),
                            GEO_DISPLAY_LIST(1, castle_inside_dl_05005D38),
                            GEO_DISPLAY_LIST(1, castle_inside_dl_05005D90),
                            GEO_DISPLAY_LIST(1, castle_inside_dl_05005DE8),
                            GEO_DISPLAY_LIST(1, castle_inside_dl_05005E40),
                            GEO_DISPLAY_LIST(1, castle_inside_dl_05005E98),
                            GEO_DISPLAY_LIST(1, castle_inside_dl_05005EF0),
                            GEO_DISPLAY_LIST(1, castle_inside_dl_05005F48),
                            GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(1, 38, 65458, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 0, 0, 0, castle_inside_dl_05007B18),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 132, 0, 0, castle_inside_dl_050091A8),
                    GEO_ANIMATED_PART(1, 132, 0, 0, castle_inside_dl_05008F80),
                    GEO_ANIMATED_PART(1, 63, 0, 84, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, castle_inside_dl_05007EB8),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 104, 0, 0, castle_inside_dl_05008808),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 87, 0, 0, castle_inside_dl_05009560),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, castle_inside_dl_050085C0),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 63, 0, 65452, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, castle_inside_dl_05008288),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 104, 0, 0, castle_inside_dl_05008D58),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 87, 0, 0, castle_inside_dl_050099A0),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, castle_inside_dl_05008B10),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(1, 78, 0, 0, castle_inside_dl_050060E0),
                GEO_ANIMATED_PART(1, -23, 65535, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, castle_inside_dl_0500A108),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout castle_inside_geo_0C000254[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(5, 0, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(5, 0, 0, 0, castle_inside_dl_05007288),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(5, 78, 0, 0, castle_inside_dl_05006A18),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(5, 132, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_SWITCH_CASE(8, NULL),
                        GEO_OPEN_NODE(),
                            GEO_DISPLAY_LIST(5, castle_inside_dl_05005CE0),
                            GEO_DISPLAY_LIST(5, castle_inside_dl_05005D38),
                            GEO_DISPLAY_LIST(5, castle_inside_dl_05005D90),
                            GEO_DISPLAY_LIST(5, castle_inside_dl_05005DE8),
                            GEO_DISPLAY_LIST(5, castle_inside_dl_05005E40),
                            GEO_DISPLAY_LIST(5, castle_inside_dl_05005E98),
                            GEO_DISPLAY_LIST(5, castle_inside_dl_05005EF0),
                            GEO_DISPLAY_LIST(5, castle_inside_dl_05005F48),
                            GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(5, 38, 65458, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(5, 0, 0, 0, castle_inside_dl_05007B18),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(5, 132, 0, 0, castle_inside_dl_050091A8),
                    GEO_ANIMATED_PART(5, 132, 0, 0, castle_inside_dl_05008F80),
                    GEO_ANIMATED_PART(5, 63, 0, 84, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 0, 0, 0, castle_inside_dl_05007EB8),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(5, 104, 0, 0, castle_inside_dl_05008808),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(5, 87, 0, 0, castle_inside_dl_05009560),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(5, 0, 0, 0, castle_inside_dl_050085C0),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(5, 63, 0, 65452, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 0, 0, 0, castle_inside_dl_05008288),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(5, 104, 0, 0, castle_inside_dl_05008D58),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(5, 87, 0, 0, castle_inside_dl_050099A0),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(5, 0, 0, 0, castle_inside_dl_05008B10),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(5, 78, 0, 0, castle_inside_dl_050060E0),
                GEO_ANIMATED_PART(5, -23, 65535, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(5, 0, 0, 0, castle_inside_dl_0500A188),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout castle_inside_geo_0C000410[] = {
    GEO_SHADOW(0, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ASM(10, geo_update_layer_transparency),
            GEO_SWITCH_CASE(2, geo_switch_anim_state),
            GEO_OPEN_NODE(),
                GEO_BRANCH(1, castle_inside_geo_0C000098),
                GEO_BRANCH(1, castle_inside_geo_0C000254),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout castle_inside_geo_0C000468[] = {
    GEO_SHADOW(1, 200, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, castle_inside_dl_050226F0),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 100, 0, 0, castle_inside_dl_050224F0),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 222, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_SWITCH_CASE(2, geo_switch_anim_state),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(1, castle_inside_dl_0501DA58),
                                GEO_DISPLAY_LIST(1, castle_inside_dl_0501DA80),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 76, 49, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, castle_inside_dl_05021398),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(1, 51, 55, 97, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 0, 0, 0, castle_inside_dl_05021760),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 74, 0, 0, castle_inside_dl_050216C0),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(1, 69, 0, 0, castle_inside_dl_05021578),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(1, 51, 55, 65439, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 0, 0, 0, castle_inside_dl_050219E8),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 74, 0, 0, castle_inside_dl_05021948),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(1, 69, 0, 0, castle_inside_dl_05021800),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -1, 27, 95, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, castle_inside_dl_05021DC0),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 100, 0, 0, castle_inside_dl_05021C78),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 95, 0, 0, castle_inside_dl_05021A88),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -89, 65474, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, castle_inside_dl_05021F20),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -1, 27, 65441, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, castle_inside_dl_05022390),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 100, 0, 0, castle_inside_dl_05022248),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 95, 0, 0, castle_inside_dl_05022058),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout castle_inside_geo_0D000448[] = {
    GEO_SHADOW(1, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, castle_inside_dl_06010D30),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 64, 0, 0, castle_inside_dl_060108A8),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 52, 65512, 65504, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 0, 0, 0, castle_inside_dl_06011EA0),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 79, 0, 0, castle_inside_dl_06011CA0),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(1, 52, 65512, 32, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 0, 0, 0, castle_inside_dl_060111A0),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 79, 0, 0, castle_inside_dl_06010F50),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -31, 4, 65497, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, castle_inside_dl_060120B0),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 45, 0, 0, castle_inside_dl_06011A80),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 52, 0, 0, castle_inside_dl_06011870),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -31, 4, 40, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, castle_inside_dl_06011FC8),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 45, 0, 0, castle_inside_dl_06011610),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 52, 0, 0, castle_inside_dl_06011400),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout castle_inside_geo_0D0005B0[] = {
    GEO_SHADOW(1, 150, 70),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00006666),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_update_layer_transparency),
            GEO_SWITCH_CASE(2, geo_switch_anim_state),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(1, castle_inside_dl_06017DD0),
                GEO_DISPLAY_LIST(5, castle_inside_dl_06017DD0),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout castle_inside_geo_0D000000[] = {
    GEO_SHADOW(1, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, castle_inside_dl_06003E30),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 132, 0, 0, castle_inside_dl_06004680),
                    GEO_OPEN_NODE(),
                        GEO_SWITCH_CASE(2, geo_switch_anim_state),
                        GEO_OPEN_NODE(),
                            GEO_DISPLAY_LIST(4, castle_inside_dl_06004C60),
                            GEO_DISPLAY_LIST(4, castle_inside_dl_06004C88),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 87, 18, 72, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, castle_inside_dl_060047E8),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 87, 18, 65464, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, castle_inside_dl_060049E0),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 334, 65322, 65486, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, castle_inside_dl_06005610),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(1, 191, 0, 0, castle_inside_dl_06005360),
                                    GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, castle_inside_dl_060055E8),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, castle_inside_dl_06005598),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout castle_inside_geo_0D000114[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 83, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 126, 65499, 0, castle_inside_dl_06007710),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(1, 25, 8, 0, castle_inside_dl_06007AC8),
                GEO_ANIMATED_PART(1, 34, 8, 0, castle_inside_dl_06007F58),
                GEO_ANIMATED_PART(1, 4, 7, 38, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 37, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 9, 65511, 3, castle_inside_dl_06008980),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(1, 4, 7, 65498, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 37, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 9, 65511, 65533, castle_inside_dl_06008CC8),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(1, 61, 65533, 52, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 17, 0, 4, castle_inside_dl_060082A0),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(1, 61, 65533, 65484, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 17, 0, 65532, castle_inside_dl_060085C8),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout castle_inside_geo_0D00027C[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(5, 0, 0, 0, NULL),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(5, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(5, 83, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(5, 126, 65499, 0, castle_inside_dl_06007788),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(5, 25, 8, 0, castle_inside_dl_06007B00),
                GEO_ANIMATED_PART(5, 34, 8, 0, castle_inside_dl_06007F58),
                GEO_ANIMATED_PART(5, 4, 7, 38, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(5, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 37, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(5, 9, 65511, 3, castle_inside_dl_06008980),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(5, 4, 7, 65498, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(5, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 37, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(5, 9, 65511, 65533, castle_inside_dl_06008CC8),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(5, 61, 65533, 52, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(5, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 17, 0, 4, castle_inside_dl_060082A0),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(5, 61, 65533, 65484, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(5, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 17, 0, 65532, castle_inside_dl_06008608),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_RETURN(),
};


const GeoLayout castle_inside_geo_0D0003E4[] = {
    GEO_CULLING_RADIUS(1000),
    GEO_OPEN_NODE(),
        GEO_SHADOW(0, 150, 100),
        GEO_OPEN_NODE(),
            GEO_SCALE(0, 0x00004000),
            GEO_OPEN_NODE(),
                GEO_ASM(10, geo_update_layer_transparency),
                GEO_SWITCH_CASE(2, geo_switch_anim_state),
                GEO_OPEN_NODE(),
                    GEO_BRANCH(1, castle_inside_geo_0D000114),
                    GEO_BRANCH(1, castle_inside_geo_0D00027C),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};
