const GeoLayout bbh_geo_0F000000[] = {
    GEO_CULLING_RADIUS(300),
    GEO_OPEN_NODE(),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, bbh_dl_08000E08),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F000028[] = {
    GEO_SHADOW(1, 200, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(4, 0, 0, 0, bbh_dl_08002C88),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_SWITCH_CASE(2, geo_switch_anim_state),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                            GEO_ANIMATED_PART(4, 0, 0, 0, bbh_dl_08002BA0),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_SWITCH_CASE(2, geo_switch_anim_state),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                            GEO_ANIMATED_PART(4, 0, 0, 0, bbh_dl_08002BA0),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_SWITCH_CASE(2, geo_switch_anim_state),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                            GEO_ANIMATED_PART(4, 0, 0, 0, bbh_dl_08002BA0),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_SWITCH_CASE(2, geo_switch_anim_state),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                            GEO_ANIMATED_PART(4, 0, 0, 0, bbh_dl_08002BA0),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(4, 0, 0, 0, bbh_dl_08002D70),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                    GEO_OPEN_NODE(),
                        GEO_DISPLAY_LIST(4, bbh_dl_08002E58),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F000ADC[] = {
    GEO_SHADOW(1, 200, 70),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, bbh_dl_08027420),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F000B08[] = {
    GEO_SHADOW(1, 200, 70),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, bbh_dl_080273C8),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F0004CC[] = {
    GEO_CULLING_RADIUS(300),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, bbh_dl_0800C718),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F0004E4[] = {
    GEO_CULLING_RADIUS(400),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, bbh_dl_0800D680),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F0005D0[] = {
    GEO_CULLING_RADIUS(500),
    GEO_OPEN_NODE(),
        GEO_SHADOW(10, 180, 240),
        GEO_OPEN_NODE(),
            GEO_SWITCH_CASE(2, geo_switch_anim_state),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(1, bbh_dl_08012D20),
                GEO_DISPLAY_LIST(1, bbh_dl_08012D48),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F000610[] = {
    GEO_CULLING_RADIUS(500),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(2, geo_switch_anim_state),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, bbh_dl_08012D20),
            GEO_DISPLAY_LIST(1, bbh_dl_08012D48),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_04037070[] = {
    GEO_CULLING_RADIUS(300),
    GEO_OPEN_NODE(),
        GEO_SHADOW(10, 180, 70),
        GEO_OPEN_NODE(),
            GEO_SWITCH_CASE(6, geo_switch_anim_state),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(5, bbh_dl_08024F88),
                GEO_DISPLAY_LIST(5, bbh_dl_08024FA8),
                GEO_DISPLAY_LIST(5, bbh_dl_08024FC8),
                GEO_DISPLAY_LIST(5, bbh_dl_08024FE8),
                GEO_DISPLAY_LIST(5, bbh_dl_08024FE8),
                GEO_DISPLAY_LIST(5, bbh_dl_08024FE8),
                GEO_CLOSE_NODE(),
            GEO_DISPLAY_LIST(4, bbh_dl_080259F8),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_04036F60[] = {
    GEO_CULLING_RADIUS(300),
    GEO_OPEN_NODE(),
        GEO_SHADOW(10, 180, 70),
        GEO_OPEN_NODE(),
            GEO_SWITCH_CASE(14, geo_switch_anim_state),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(1, bbh_dl_08019318),
                GEO_DISPLAY_LIST(1, bbh_dl_08019378),
                GEO_DISPLAY_LIST(1, bbh_dl_080193D8),
                GEO_DISPLAY_LIST(1, bbh_dl_08019438),
                GEO_DISPLAY_LIST(1, bbh_dl_04037000),
                GEO_DISPLAY_LIST(1, bbh_dl_04037100),
                GEO_DISPLAY_LIST(1, bbh_dl_04037200),
                GEO_DISPLAY_LIST(1, bbh_dl_04037300),
                GEO_DISPLAY_LIST(1, bbh_dl_04037400),
                GEO_DISPLAY_LIST(1, bbh_dl_04037500),
                GEO_DISPLAY_LIST(1, bbh_dl_04037600),
                GEO_DISPLAY_LIST(1, bbh_dl_04037700),
                GEO_DISPLAY_LIST(1, bbh_dl_04037800),
                GEO_DISPLAY_LIST(1, bbh_dl_04037900),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F0006E4[] = {
    GEO_SHADOW(1, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_0801D760),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                    GEO_OPEN_NODE(),
                        GEO_DISPLAY_LIST(4, bbh_dl_0801B690),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_OPEN_NODE(),
                    GEO_SWITCH_CASE(2, geo_switch_anim_state),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 48, 0, 0, bbh_dl_0801B5C8),
                        GEO_ANIMATED_PART(1, 48, 0, 0, bbh_dl_0801B5F0),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -60, 65520, 45, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_0801CE20),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -60, 65520, 65491, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_0801CF78),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F000AB0[] = {
    GEO_SHADOW(1, 200, 70),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00010000),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, bbh_dl_08028B78),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F000A30[] = {
    GEO_CULLING_RADIUS(500),
    GEO_OPEN_NODE(),
        GEO_SHADOW(10, 180, 70),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, bbh_dl_08024BB8),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F0007B8[] = {
    GEO_SHADOW(1, 200, 70),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00006000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                        GEO_OPEN_NODE(),
                            GEO_DISPLAY_LIST(4, bbh_dl_08022D08),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 0, 57, 65476, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 91, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_08023270),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 0, 55, 62, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 91, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_08023378),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_08023480),
                    GEO_SWITCH_CASE(2, geo_switch_anim_state),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(4, 0, 0, 0, bbh_dl_08022B58),
                        GEO_ANIMATED_PART(4, 0, 0, 0, bbh_dl_08022B88),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F0008F4[] = {
    GEO_SHADOW(1, 200, 70),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00006000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                        GEO_OPEN_NODE(),
                            GEO_DISPLAY_LIST(4, bbh_dl_08022D78),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 0, 57, 65476, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 91, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_08023270),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 0, 55, 62, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 91, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_08023378),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_08023480),
                    GEO_SWITCH_CASE(2, geo_switch_anim_state),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(4, 0, 0, 0, bbh_dl_08022B58),
                        GEO_ANIMATED_PART(4, 0, 0, 0, bbh_dl_08022B88),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F000640[] = {
    GEO_SHADOW(1, 200, 280),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00029999),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(4, bbh_dl_08022D08),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F0001C0[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, bbh_dl_08006660),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F0001A8[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, bbh_dl_080057F8),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F0004FC[] = {
    GEO_SHADOW(1, 100, 100),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(5, bbh_dl_0800DFE0),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F000518[] = {
    GEO_SHADOW(1, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_08011710),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, -45, 65516, 65481, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_08010840),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -45, 65516, 55, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_08010968),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 250, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(5, 0, 0, 0, bbh_dl_08010B80),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F0001D8[] = {
    GEO_SHADOW(1, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 281, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_0800ABE8),
                            GEO_ANIMATED_PART(1, 113, 65384, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(1, 74, 0, 0, NULL),
                                    GEO_OPEN_NODE(),
                                        GEO_ANIMATED_PART(1, 96, 0, 0, NULL),
                                        GEO_OPEN_NODE(),
                                            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                                            GEO_OPEN_NODE(),
                                                GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                                                GEO_OPEN_NODE(),
                                                    GEO_DISPLAY_LIST(4, bbh_dl_0800A5F8),
                                                    GEO_CLOSE_NODE(),
                                                GEO_CLOSE_NODE(),
                                            GEO_CLOSE_NODE(),
                                        GEO_CLOSE_NODE(),
                                    GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_0800A998),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_ANIMATED_PART(4, 0, 0, 0, bbh_dl_0800A758),
                            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                                GEO_OPEN_NODE(),
                                    GEO_DISPLAY_LIST(4, bbh_dl_0800A068),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_ANIMATED_PART(1, 1, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(1, 209, 0, 0, NULL),
                                    GEO_OPEN_NODE(),
                                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                                        GEO_OPEN_NODE(),
                                            GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                                            GEO_OPEN_NODE(),
                                                GEO_DISPLAY_LIST(4, bbh_dl_0800A1D0),
                                                GEO_CLOSE_NODE(),
                                            GEO_CLOSE_NODE(),
                                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                                        GEO_OPEN_NODE(),
                                            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                                            GEO_OPEN_NODE(),
                                                GEO_ANIMATED_PART(1, 95, 0, 0, NULL),
                                                GEO_OPEN_NODE(),
                                                    GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                                                    GEO_OPEN_NODE(),
                                                        GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                                                        GEO_OPEN_NODE(),
                                                            GEO_DISPLAY_LIST(4, bbh_dl_0800A428),
                                                            GEO_CLOSE_NODE(),
                                                        GEO_CLOSE_NODE(),
                                                    GEO_CLOSE_NODE(),
                                                GEO_CLOSE_NODE(),
                                            GEO_CLOSE_NODE(),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_ANIMATED_PART(1, 1, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(1, 209, 0, 0, NULL),
                                    GEO_OPEN_NODE(),
                                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                                        GEO_OPEN_NODE(),
                                            GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                                            GEO_OPEN_NODE(),
                                                GEO_DISPLAY_LIST(4, bbh_dl_0800A338),
                                                GEO_CLOSE_NODE(),
                                            GEO_CLOSE_NODE(),
                                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                                        GEO_OPEN_NODE(),
                                            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                                            GEO_OPEN_NODE(),
                                                GEO_ANIMATED_PART(1, 95, 0, 0, NULL),
                                                GEO_OPEN_NODE(),
                                                    GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                                                    GEO_OPEN_NODE(),
                                                        GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                                                        GEO_OPEN_NODE(),
                                                            GEO_DISPLAY_LIST(4, bbh_dl_0800A510),
                                                            GEO_CLOSE_NODE(),
                                                        GEO_CLOSE_NODE(),
                                                    GEO_ASM(0, geo_update_projectile_pos_from_parent),
                                                    GEO_CLOSE_NODE(),
                                                GEO_CLOSE_NODE(),
                                            GEO_CLOSE_NODE(),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_0800A8D0),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0F00066C[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00029999),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(4, bbh_dl_08022D08),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0C000224[] = {
    GEO_SHADOW(1, 150, 70),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00006666),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_update_layer_transparency),
            GEO_SWITCH_CASE(2, geo_switch_anim_state),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(1, bbh_dl_0500C1B0),
                GEO_DISPLAY_LIST(5, bbh_dl_0500C1B0),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0C000188[] = {
    GEO_SHADOW(1, 150, 80),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, bbh_dl_05006A68),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0C0000D8[] = {
    GEO_SHADOW(1, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_05005190),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, -7, 65527, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_05005680),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 156, 65527, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_05005408),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -3, 17, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_05004EE8),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0C0001B4[] = {
    GEO_SHADOW(1, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_050098E8),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, -141, 64990, 218, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_05008CB0),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0C000000[] = {
    GEO_SHADOW(1, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_05001F98),
                    GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_05001B20),
                    GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_05002140),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_05001D68),
                    GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_05001978),
                    GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_050022E0),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0C0000C0[] = {
    GEO_CULLING_RADIUS(300),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, bbh_dl_05002FB0),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0C000274[] = {
    GEO_CULLING_RADIUS(300),
    GEO_OPEN_NODE(),
        GEO_SHADOW(0, 150, 100),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, bbh_dl_0500F7D8),
            GEO_DISPLAY_LIST(1, bbh_dl_0500FC28),
            GEO_DISPLAY_LIST(4, bbh_dl_05010100),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0D0000DC[] = {
    GEO_SHADOW(1, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                    GEO_OPEN_NODE(),
                        GEO_DISPLAY_LIST(4, bbh_dl_06006880),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 54, 0, 0, bbh_dl_06006758),
                    GEO_ANIMATED_PART(1, 54, 0, 0, bbh_dl_06006A88),
                    GEO_ANIMATED_PART(1, 57, 65488, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(4, 0, 0, 0, bbh_dl_06006BD0),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 57, 65488, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(4, 0, 0, 0, bbh_dl_06006D00),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0D000394[] = {
    GEO_SHADOW(1, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 65507, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, -1, 113, 112, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 198, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 195, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(4, 0, 0, 0, bbh_dl_06014378),
                                    GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(4, 0, 0, 0, bbh_dl_06014270),
                                GEO_CLOSE_NODE(),
                            GEO_ANIMATED_PART(4, 0, 0, 0, bbh_dl_06014188),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -1, 109, 65420, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 198, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 195, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(4, 0, 0, 0, bbh_dl_06014378),
                                    GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(4, 0, 0, 0, bbh_dl_06014270),
                                GEO_CLOSE_NODE(),
                            GEO_ANIMATED_PART(4, 0, 0, 0, bbh_dl_06014188),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                        GEO_OPEN_NODE(),
                            GEO_DISPLAY_LIST(4, bbh_dl_060139F8),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -29, 65479, 28, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 158, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(4, bbh_dl_06013AE8),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(4, 0, 0, 0, bbh_dl_06013CB8),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -29, 55, 28, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 157, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(4, bbh_dl_06013BD0),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(4, 0, 0, 0, bbh_dl_06013DA0),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -1, 65420, 65425, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 198, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 195, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(4, 0, 0, 0, bbh_dl_06014378),
                                    GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(4, 0, 0, 0, bbh_dl_06014270),
                                GEO_CLOSE_NODE(),
                            GEO_ANIMATED_PART(4, 0, 0, 0, bbh_dl_06014188),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -1, 65420, 112, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 195, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 199, 0, 0, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(4, 0, 0, 0, bbh_dl_06014378),
                                    GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(4, 0, 0, 0, bbh_dl_06014270),
                                GEO_CLOSE_NODE(),
                            GEO_ANIMATED_PART(4, 0, 0, 0, bbh_dl_06014188),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_060140F0),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0D00001C[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(20, geo_switch_anim_state),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(4, bbh_dl_060041D8),
            GEO_DISPLAY_LIST(4, bbh_dl_060041F0),
            GEO_DISPLAY_LIST(4, bbh_dl_06004208),
            GEO_DISPLAY_LIST(4, bbh_dl_06004220),
            GEO_DISPLAY_LIST(4, bbh_dl_06004208),
            GEO_DISPLAY_LIST(4, bbh_dl_060041F0),
            GEO_DISPLAY_LIST(4, bbh_dl_060041D8),
            GEO_DISPLAY_LIST(4, bbh_dl_060041D8),
            GEO_DISPLAY_LIST(4, bbh_dl_060041D8),
            GEO_DISPLAY_LIST(4, bbh_dl_060041F0),
            GEO_DISPLAY_LIST(4, bbh_dl_06004208),
            GEO_DISPLAY_LIST(4, bbh_dl_06004220),
            GEO_DISPLAY_LIST(4, bbh_dl_06004208),
            GEO_DISPLAY_LIST(4, bbh_dl_060041F0),
            GEO_DISPLAY_LIST(4, bbh_dl_060041D8),
            GEO_DISPLAY_LIST(4, bbh_dl_060041D8),
            GEO_DISPLAY_LIST(4, bbh_dl_060041D8),
            GEO_DISPLAY_LIST(4, bbh_dl_060041D8),
            GEO_DISPLAY_LIST(4, bbh_dl_060041D8),
            GEO_DISPLAY_LIST(4, bbh_dl_060041D8),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0D000000[] = {
    GEO_SHADOW(1, 155, 200),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(4, bbh_dl_06002080),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0D000230[] = {
    GEO_CULLING_RADIUS(5000),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_0600CFD0),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 1295, 0, 0, bbh_dl_0600C8B8),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 916, 0, 0, bbh_dl_0600C468),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 874, 0, 0, bbh_dl_0600BAF8),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(4, bbh_dl_0600DFA8),
                                GEO_ANIMATED_PART(1, 30, 444, 65530, NULL),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_0600C030),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -893, 65046, 65530, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_0600D440),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 1300, 0, 0, bbh_dl_0600D6D8),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -1086, 91, 64836, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_0600DE38),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 902, 700, 64751, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_0600DA88),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -1086, 91, 698, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_0600DC60),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 902, 700, 783, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_0600D8B0),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0D0001A0[] = {
    GEO_SHADOW(1, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ASM(0, geo_snufit_move_mask),
            GEO_TRANSLATE_NODE(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(1, bbh_dl_06009748),
                GEO_CLOSE_NODE(),
            GEO_DISPLAY_LIST(1, bbh_dl_06009498),
            GEO_DISPLAY_LIST(1, bbh_dl_06009938),
            GEO_DISPLAY_LIST(1, bbh_dl_06009B68),
            GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ASM(0, geo_snufit_scale_body),
                GEO_SCALE(0, 0x00000000),
                GEO_OPEN_NODE(),
                    GEO_DISPLAY_LIST(4, bbh_dl_06009A10),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_16000720[] = {
    GEO_TRANSLATE_NODE(0, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, -300, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_OPEN_NODE(),
                    GEO_RENDER_RANGE(-2048, 3500),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_03014D40),
                        GEO_CLOSE_NODE(),
                    GEO_RENDER_RANGE(3500, 32767),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_03015158),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_120005B0[] = {
    GEO_CULLING_RADIUS(700),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, bbh_dl_0701F2E8),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_120005C8[] = {
    GEO_CULLING_RADIUS(600),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, bbh_dl_0701F5F8),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_120005E0[] = {
    GEO_CULLING_RADIUS(650),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, bbh_dl_0701F7E8),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_120005F8[] = {
    GEO_CULLING_RADIUS(300),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, bbh_dl_0701FAB0),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_12000610[] = {
    GEO_CULLING_RADIUS(1000),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, bbh_dl_0701FD28),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_12000628[] = {
    GEO_CULLING_RADIUS(600),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(4, bbh_dl_0701FFE8),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_12000640[] = {
    GEO_CULLING_RADIUS(2300),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, bbh_dl_070202F0),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_12000658[] = {
    GEO_CULLING_RADIUS(800),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, bbh_dl_070206F0),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_16000388[] = {
    GEO_CULLING_RADIUS(350),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(1, bbh_dl_03008F98),
        GEO_DISPLAY_LIST(1, bbh_dl_03009A50),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0301CF64[] = {
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(4, bbh_dl_0302FEE8),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0301CF8C[] = {
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(4, bbh_dl_03030FA0),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0301CF50[] = {
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(4, bbh_dl_03032088),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_16000FE8[] = {
    GEO_SHADOW(0, 155, 400),
    GEO_BRANCH(1, bbh_geo_0301CF64),
    GEO_BRANCH_AND_LINK(NULL),
    GEO_SHADOW(0, 155, 400),
    GEO_BRANCH(1, bbh_geo_0301CF8C),
    GEO_BRANCH_AND_LINK(NULL),
    GEO_SHADOW(0, 155, 400),
    GEO_BRANCH(1, bbh_geo_0301CF50),
    GEO_BRANCH_AND_LINK(NULL),
    GEO_CULLING_RADIUS(800),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(4, bbh_dl_03032170),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_16001000[] = {
    GEO_SHADOW(0, 155, 400),
    GEO_BRANCH(1, bbh_geo_0301CF8C),
    GEO_BRANCH_AND_LINK(NULL),
    GEO_SHADOW(0, 155, 400),
    GEO_BRANCH(1, bbh_geo_0301CF50),
    GEO_BRANCH_AND_LINK(NULL),
    GEO_CULLING_RADIUS(800),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(4, bbh_dl_03032170),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_16001018[] = {
    GEO_SHADOW(0, 155, 400),
    GEO_BRANCH(1, bbh_geo_0301CF50),
    GEO_BRANCH_AND_LINK(NULL),
    GEO_CULLING_RADIUS(800),
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(4, bbh_dl_03032170),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_0301CF78[] = {
    GEO_OPEN_NODE(),
        GEO_DISPLAY_LIST(4, bbh_dl_03033258),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_16001048[] = {
    GEO_SHADOW(0, 155, 400),
    GEO_BRANCH(1, bbh_geo_0301CF78),
    GEO_BRANCH_AND_LINK(NULL),
};


const GeoLayout bbh_geo_160005F8[] = {
    GEO_TRANSLATE_NODE(0, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, -300, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_OPEN_NODE(),
                    GEO_RENDER_RANGE(-2048, 3500),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_03014BE0),
                        GEO_CLOSE_NODE(),
                    GEO_RENDER_RANGE(3500, 32767),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_03015078),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_1600068C[] = {
    GEO_TRANSLATE_NODE(0, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, -300, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_OPEN_NODE(),
                    GEO_RENDER_RANGE(-2048, 3500),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_03014C90),
                        GEO_CLOSE_NODE(),
                    GEO_RENDER_RANGE(3500, 32767),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_030150E8),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_160007B4[] = {
    GEO_TRANSLATE_NODE(0, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, -300, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_OPEN_NODE(),
                    GEO_RENDER_RANGE(-2048, 1000),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_03013E28),
                        GEO_OPEN_NODE(),
                            GEO_DISPLAY_LIST(5, bbh_dl_03014250),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_RENDER_RANGE(1000, 32767),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_03013E28),
                        GEO_OPEN_NODE(),
                            GEO_DISPLAY_LIST(6, bbh_dl_03014280),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_16000868[] = {
    GEO_TRANSLATE_NODE(0, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, -300, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_OPEN_NODE(),
                    GEO_RENDER_RANGE(-2048, 1000),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_03013E28),
                        GEO_OPEN_NODE(),
                            GEO_DISPLAY_LIST(5, bbh_dl_030142B0),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_RENDER_RANGE(1000, 32767),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_03013E28),
                        GEO_OPEN_NODE(),
                            GEO_DISPLAY_LIST(6, bbh_dl_030142E0),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_1600091C[] = {
    GEO_TRANSLATE_NODE(0, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, -300, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_OPEN_NODE(),
                    GEO_RENDER_RANGE(-2048, 1000),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_03013E28),
                        GEO_OPEN_NODE(),
                            GEO_DISPLAY_LIST(5, bbh_dl_03014310),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_RENDER_RANGE(1000, 32767),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_03013E28),
                        GEO_OPEN_NODE(),
                            GEO_DISPLAY_LIST(6, bbh_dl_03014340),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_160009D0[] = {
    GEO_TRANSLATE_NODE(0, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, -300, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_OPEN_NODE(),
                    GEO_RENDER_RANGE(-2048, 1000),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_03013E28),
                        GEO_OPEN_NODE(),
                            GEO_DISPLAY_LIST(1, bbh_dl_03014540),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_RENDER_RANGE(1000, 32767),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_03013E28),
                        GEO_OPEN_NODE(),
                            GEO_DISPLAY_LIST(2, bbh_dl_03014528),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout bbh_geo_160003A8[] = {
    GEO_TRANSLATE_NODE(0, 0, 0, 0),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, -300, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_OPEN_NODE(),
                    GEO_RENDER_RANGE(-2048, 3500),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_03013E28),
                        GEO_CLOSE_NODE(),
                    GEO_RENDER_RANGE(3500, 32767),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, bbh_dl_03014100),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};
