const GeoLayout thi_geo_0C0001BC[] = {
    GEO_SHADOW(1, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 63, 65474, thi_dl_050138B0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, thi_dl_05012910),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 132, 0, 0, thi_dl_05013160),
                    GEO_OPEN_NODE(),
                        GEO_SWITCH_CASE(2, geo_switch_anim_state),
                        GEO_OPEN_NODE(),
                            GEO_DISPLAY_LIST(4, thi_dl_05013350),
                            GEO_DISPLAY_LIST(4, thi_dl_05013378),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 87, 18, 72, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, thi_dl_050136A0),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 87, 18, 65464, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, thi_dl_050134A8),
                        GEO_ASM(0, geo_update_projectile_pos_from_parent),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout thi_geo_0C000290[] = {
    GEO_SHADOW(1, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, -18, 65502, 10, thi_dl_05015368),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, thi_dl_05015330),
                GEO_ANIMATED_PART(1, 0, 0, 0, thi_dl_050152F8),
                GEO_ANIMATED_PART(1, 0, 0, 0, thi_dl_050152C0),
                GEO_ANIMATED_PART(1, 0, 0, 0, thi_dl_05015288),
                GEO_ANIMATED_PART(1, 0, 0, 0, thi_dl_05015250),
                GEO_ANIMATED_PART(1, 0, 0, 0, thi_dl_05015218),
                GEO_ANIMATED_PART(1, 0, 0, 0, thi_dl_050151E0),
                GEO_ANIMATED_PART(1, 0, 0, 0, thi_dl_050151A8),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout thi_geo_0C000328[] = {
    GEO_SHADOW(1, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 72, 65529, thi_dl_05016A48),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 0, 0, 0, thi_dl_05016738),
                    GEO_ANIMATED_PART(1, -1, 55, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 77, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, thi_dl_05016418),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 0, 65488, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 88, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, thi_dl_050164E0),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -1, 55, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 77, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, thi_dl_050165A8),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, 0, 65488, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 88, 0, 0, NULL),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 0, 0, 0, thi_dl_05016670),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout thi_geo_0C000030[] = {
    GEO_SHADOW(1, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                    GEO_OPEN_NODE(),
                        GEO_DISPLAY_LIST(4, thi_dl_0500C278),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, 157, 0, 0, NULL),
                    GEO_OPEN_NODE(),
                        GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                        GEO_OPEN_NODE(),
                            GEO_DISPLAY_LIST(4, thi_dl_0500E678),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 143, 0, 0, NULL),
                        GEO_OPEN_NODE(),
                            GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                            GEO_OPEN_NODE(),
                                GEO_DISPLAY_LIST(4, thi_dl_0500E1D8),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(1, 143, 0, 0, NULL),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(4, 157, 0, 0, thi_dl_0500E518),
                    GEO_ANIMATED_PART(4, 157, 0, 0, thi_dl_0500E430),
                    GEO_ANIMATED_PART(4, 157, 0, 0, thi_dl_0500E2F8),
                    GEO_ANIMATED_PART(1, -16, 23, 51, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, thi_dl_0500DDF8),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 39, 0, 0, thi_dl_0500DD70),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 41, 0, 0, thi_dl_0500DC18),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -16, 23, 65487, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, thi_dl_0500E060),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 39, 0, 0, thi_dl_0500DFD8),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 41, 0, 0, thi_dl_0500DE80),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout thi_geo_0500C778[] = {
    GEO_SHADOW(1, 150, 100),
    GEO_OPEN_NODE(),
        GEO_SCALE(0, 0x00004000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
                GEO_OPEN_NODE(),
                    GEO_BILLBOARD_WITH_PARAMS(0, 0, 0, 0),
                    GEO_OPEN_NODE(),
                        GEO_DISPLAY_LIST(4, thi_dl_0500C278),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(1, -31, 0, 51, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, thi_dl_0500BE98),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 39, 0, 0, thi_dl_0500BE10),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 41, 0, 0, thi_dl_0500BCB8),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(1, -31, 0, 65487, NULL),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(1, 0, 0, 0, thi_dl_0500C100),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(1, 39, 0, 0, thi_dl_0500C078),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(1, 41, 0, 0, thi_dl_0500BF20),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};


const GeoLayout thi_geo_0C000000[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_SWITCH_CASE(2, geo_switch_anim_state),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(1, thi_dl_05004E80),
            GEO_DISPLAY_LIST(1, thi_dl_05005978),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_END(),
};
