GeoLayout king_bobomb_geo[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 150, 300),
    GEO_OPEN_NODE(),
        GEO_SCALE(LAYER_FORCE, 0x4000),
        GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, 0),
                GEO_OPEN_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, 0),
                    GEO_OPEN_NODE(),
                        GEO_BILLBOARD_WITH_PARAMS(LAYER_FORCE, 0, 0, 0),
                        GEO_OPEN_NODE(),
                            GEO_DISPLAY_LIST(LAYER_ALPHA, DL_king_bobomb_geo_0x500b188),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -243, 0, 0),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, 0),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 488, 0, 0, 0),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 110, 0, 0, 0),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, DL_king_bobomb_geo_0x500ad08),
                                GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, 0),
                                GEO_OPEN_NODE(),
                                    GEO_BILLBOARD_WITH_PARAMS(LAYER_FORCE, 0, 0, 0),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(LAYER_ALPHA, DL_king_bobomb_geo_0x500a5d8),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, DL_king_bobomb_geo_0x500b2d0),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, DL_king_bobomb_geo_0x500b418),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, DL_king_bobomb_geo_0x500b6c0),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 243, 0, 0),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, 0),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 488, 0, 0, 0),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 110, 0, 0, 0),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, DL_king_bobomb_geo_0x500b068),
                                GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, 0),
                                GEO_OPEN_NODE(),
                                    GEO_BILLBOARD_WITH_PARAMS(LAYER_FORCE, 0, 0, 0),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(LAYER_ALPHA, DL_king_bobomb_geo_0x500a890),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -1, 36, 0),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, 0),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 548, 0, 0, 0),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, 0),
                                GEO_OPEN_NODE(),
                                    GEO_BILLBOARD_WITH_PARAMS(LAYER_FORCE, 0, 0, 0),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(LAYER_ALPHA, DL_king_bobomb_geo_0x500a4f0),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 189, 0, 0, 0),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, 0),
                                    GEO_OPEN_NODE(),
                                        GEO_BILLBOARD_WITH_PARAMS(LAYER_FORCE, 0, 0, 0),
                                        GEO_OPEN_NODE(),
                                            GEO_DISPLAY_LIST(LAYER_ALPHA, DL_king_bobomb_geo_0x500a6c0),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                    GEO_ASM(0, geo_update_held_mario_pos),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 1, 36, 0),
                    GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, 0),
                        GEO_OPEN_NODE(),
                            GEO_ANIMATED_PART(LAYER_OPAQUE, 548, 0, 0, 0),
                            GEO_OPEN_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, 0),
                                GEO_OPEN_NODE(),
                                    GEO_BILLBOARD_WITH_PARAMS(LAYER_FORCE, 0, 0, 0),
                                    GEO_OPEN_NODE(),
                                        GEO_DISPLAY_LIST(LAYER_ALPHA, DL_king_bobomb_geo_0x500a7a8),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                                GEO_ANIMATED_PART(LAYER_OPAQUE, 189, 0, 0, 0),
                                GEO_OPEN_NODE(),
                                    GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, 0),
                                    GEO_OPEN_NODE(),
                                        GEO_BILLBOARD_WITH_PARAMS(LAYER_FORCE, 0, 0, 0),
                                        GEO_OPEN_NODE(),
                                            GEO_DISPLAY_LIST(LAYER_ALPHA, DL_king_bobomb_geo_0x500a978),
                                        GEO_CLOSE_NODE(),
                                    GEO_CLOSE_NODE(),
                                GEO_CLOSE_NODE(),
                            GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                    GEO_CLOSE_NODE(),
                GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
GEO_CLOSE_NODE(),
GEO_END(),
};

